"""
Counterfactual modality packet utilities.

A counterfactual packet stores one latent scene/trajectory state rendered under
multiple modalities. The file format is a portable ``.npz`` bundle containing:

    - ``metadata_json``: JSON with latent state, modality names, CRLB metadata,
      and annotation schema.
    - ``image__<modality>`` arrays: one image per selected modality.
    - ``fisher__<modality>`` arrays: Fisher matrices per modality when generated
      by the dataset packet workflow.
    - ``mask__<name>`` arrays: geometry/supported/ignore masks when generated by
      the dataset packet workflow.

Rendering is handled by the simulator/dataset workflow; this module owns the
portable packet contract and validation.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Mapping

import numpy as np
from json_utils import json_safe_with_nonfinite_tags
from shared_constants import MATCHED_INFORMATION_MASK_ROLES
from packet_validation import _validate_profile_card_contract


_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


def _safe_key(name: str) -> str:
    out = _SAFE_NAME_RE.sub("_", str(name).strip())
    return out.strip("_") or "unnamed"


def _validated_image_array(label: str, image: Any) -> np.ndarray:
    arr = np.asarray(image)
    if arr.ndim < 2:
        raise ValueError(f"Image for modality {label!r} must be at least 2D; got {arr.shape}.")
    if arr.dtype == object or not np.issubdtype(arr.dtype, np.number):
        raise ValueError(f"Image for modality {label!r} must have a numeric non-object dtype; got {arr.dtype}.")
    if np.iscomplexobj(arr):
        raise ValueError(f"Image for modality {label!r} must be real-valued, not complex.")
    arr = np.asarray(arr, dtype=float)
    if np.any(~np.isfinite(arr)):
        raise ValueError(f"Image for modality {label!r} must contain only finite values.")
    return arr


def _validated_mask_array(name: str, mask: Any, image_shape: tuple[int, ...]) -> np.ndarray:
    arr = np.asarray(mask)
    if arr.shape != image_shape:
        raise ValueError(f"Mask {name!r} has shape {arr.shape}, expected {image_shape}.")
    if arr.dtype == object or not (np.issubdtype(arr.dtype, np.bool_) or np.issubdtype(arr.dtype, np.number)):
        raise ValueError(f"Mask {name!r} must have boolean or numeric dtype; got {arr.dtype}.")
    if np.iscomplexobj(arr):
        raise ValueError(f"Mask {name!r} must be real-valued, not complex.")
    numeric = np.asarray(arr)
    if np.any(~np.isfinite(numeric.astype(float, copy=False))):
        raise ValueError(f"Mask {name!r} must contain only finite values.")
    values = np.unique(numeric)
    if "loss_weight" in name:
        if np.any(values < 0) or np.any(values > 255):
            raise ValueError(f"Loss-weight mask {name!r} must lie in [0, 255].")
        return numeric.astype(np.uint8, copy=False)
    if not np.all(np.isin(values, [0, 1, 255, False, True])):
        raise ValueError(f"Mask {name!r} must be binary/bool with values 0/1 or 0/255; got values {values[:8]!r}.")
    return np.where(numeric.astype(float, copy=False) > 0.0, 255, 0).astype(np.uint8)


def _safe_key_map(names: list[str], *, kind: str) -> dict[str, str]:
    """Map storage-safe keys back to original labels, rejecting collisions."""
    mapping: dict[str, str] = {}
    for name in names:
        safe = _safe_key(name)
        if safe in mapping and mapping[safe] != name:
            raise ValueError(
                f"Counterfactual packet {kind} labels {mapping[safe]!r} and "
                f"{name!r} both map to storage key {safe!r}."
            )
        mapping[safe] = name
    return mapping


def _mask_names_cover_modalities(mask_names: set[str], modalities: set[str]) -> set[str]:
    """Return modalities that have at least one modality-prefixed mask name."""
    covered: set[str] = set()
    for modality in modalities:
        prefix = f"{modality}__"
        safe_prefix = f"{_safe_key(modality)}__"
        if any(name == modality or name.startswith(prefix) or name.startswith(safe_prefix) for name in mask_names):
            covered.add(modality)
    return covered


_MATCHED_INFORMATION_MASK_ROLES = MATCHED_INFORMATION_MASK_ROLES


def _required_mask_roles_present(mask_names: set[str], modality: str) -> set[str]:
    roles = set()
    prefixes = (f"{modality}__", f"{_safe_key(modality)}__")
    for name in mask_names:
        for prefix in prefixes:
            if not name.startswith(prefix):
                continue
            remainder = name[len(prefix):]
            for role in _MATCHED_INFORMATION_MASK_ROLES:
                if remainder == role or remainder.startswith(f"{role}__"):
                    roles.add(role)
    return roles


def _mask_role_and_suffix(name: str, modality: str) -> tuple[str, str] | None:
    prefixes = (f"{modality}__", f"{_safe_key(modality)}__")
    for prefix in prefixes:
        if not name.startswith(prefix):
            continue
        remainder = name[len(prefix):]
        for role in _MATCHED_INFORMATION_MASK_ROLES:
            if remainder == role:
                return role, ""
            if remainder.startswith(f"{role}__"):
                return role, remainder[len(role) + 2:]
    return None


def _validate_matched_mask_semantics(
    mask_arrays: Mapping[str, np.ndarray],
    modalities: set[str],
) -> None:
    """Validate semantic invariants across per-particle supervision sidecars."""
    for modality in sorted(modalities):
        grouped: dict[str, dict[str, np.ndarray]] = {}
        for name, arr in mask_arrays.items():
            parsed = _mask_role_and_suffix(str(name), modality)
            if parsed is None:
                continue
            role, suffix = parsed
            grouped.setdefault(suffix, {})[role] = np.asarray(arr)
        for suffix, roles in grouped.items():
            missing = set(_MATCHED_INFORMATION_MASK_ROLES) - set(roles)
            if missing:
                continue
            label = f"{modality}::{suffix or 'default'}"
            geometry = np.asarray(roles["mask_geometry"]) > 0
            supported = np.asarray(roles["mask_supported"]) > 0
            ignored = np.asarray(roles["ignore_mask"]) > 0
            loss_weight = np.asarray(roles["loss_weight"], dtype=float)
            if np.any(supported & ~geometry):
                raise ValueError(
                    f"Matched packet masks for {label} violate mask_supported subset mask_geometry."
                )
            if np.any(ignored & ~geometry):
                raise ValueError(
                    f"Matched packet masks for {label} violate ignore_mask subset mask_geometry."
                )
            expected_ignore = geometry & ~supported
            if not np.array_equal(ignored, expected_ignore):
                raise ValueError(
                    f"Matched packet masks for {label} violate ignore_mask == mask_geometry & ~mask_supported."
                )
            if np.any(loss_weight[~supported] > 0.0):
                raise ValueError(
                    f"Matched packet masks for {label} have positive loss_weight outside mask_supported."
                )
            if np.any(supported) and not np.any(loss_weight[supported] > 0.0):
                raise ValueError(
                    f"Matched packet masks for {label} have supported pixels but no positive loss_weight."
                )


def _validate_modality_profile_cards(
    packet_metadata: Mapping[str, Any],
    modalities: set[str],
) -> None:
    modality_metadata = packet_metadata.get("modality_metadata")
    if not isinstance(modality_metadata, Mapping):
        raise ValueError(
            "Matched-modality information packets require metadata['modality_metadata']."
        )
    missing_records = sorted(modalities - {str(key) for key in modality_metadata})
    if missing_records:
        raise ValueError(
            "Matched-modality information packets require modality metadata for "
            f"every modality; missing {missing_records!r}."
        )
    for modality in sorted(modalities):
        record = modality_metadata.get(modality)
        if not isinstance(record, Mapping):
            raise ValueError(f"metadata['modality_metadata'][{modality!r}] must be a mapping.")
        card = record.get("modality_profile_card")
        if not isinstance(card, Mapping):
            raise ValueError(f"Modality {modality!r} is missing modality_profile_card metadata.")
        _validate_profile_card_contract(modality, card)


def build_counterfactual_modality_packet(
    *,
    latent_state: Mapping[str, Any],
    images_by_modality: Mapping[str, np.ndarray],
    masks: Mapping[str, np.ndarray] | None = None,
    raw_images_by_modality: Mapping[str, np.ndarray] | None = None,
    rendered_signal_frame_by_modality: Mapping[str, np.ndarray] | None = None,
    reference_frame_by_modality: Mapping[str, np.ndarray] | None = None,
    noise_variance_by_modality: Mapping[str, np.ndarray] | None = None,
    fisher_by_modality: Mapping[str, np.ndarray] | None = None,
    crlb_by_modality: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
) -> dict[str, Any]:
    """
    Build an in-memory counterfactual packet.

    Parameters
    ----------
    latent_state:
        Machine-readable description of the shared particle state, trajectory
        slice, seed, frame index, or other variables common to all modalities.
    images_by_modality:
        Mapping from modality label to rendered image. All images must share
        shape so they are valid counterfactual observations of the same scene.
    masks:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach supervision masks such as ``mask_geometry``,
        ``mask_supported``, and ``ignore_mask``.
    fisher_by_modality:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach per-modality Fisher matrices on the shared parameter
        frame.
    crlb_by_modality:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach per-modality CRLB dictionaries.
    metadata:
        Optional additional packet-level metadata.
    require_information_fields:
        Require masks, Fisher matrices, and CRLB dictionaries for every modality.
        Dataset-generated matched-modality information packets enable this.
    """
    if len(images_by_modality) < 2:
        raise ValueError("images_by_modality must contain at least two modalities.")

    images = {
        str(modality): _validated_image_array(str(modality), image)
        for modality, image in images_by_modality.items()
    }
    shapes = {image.shape for image in images.values()}
    if len(shapes) != 1:
        raise ValueError(
            "All modality images in a counterfactual packet must share shape; "
            f"got {sorted(shapes)!r}."
        )

    image_shape = next(iter(shapes))
    mask_arrays = {
        str(name): _validated_mask_array(str(name), mask, image_shape)
        for name, mask in (masks or {}).items()
    }
    raw_images = {
        str(modality): _validated_image_array(str(modality), image)
        for modality, image in (raw_images_by_modality or {}).items()
    }
    if raw_images and set(raw_images) != set(images):
        raise ValueError("raw_images_by_modality must use the same modality labels as images_by_modality.")
    rendered_signal_frames = {
        str(modality): _validated_image_array(str(modality), image)
        for modality, image in (rendered_signal_frame_by_modality or {}).items()
    }
    if rendered_signal_frames and set(rendered_signal_frames) != set(images):
        raise ValueError("rendered_signal_frame_by_modality must use the same modality labels as images_by_modality.")
    reference_frames = {
        str(modality): _validated_image_array(str(modality), image)
        for modality, image in (reference_frame_by_modality or {}).items()
    }
    if reference_frames and set(reference_frames) != set(images):
        raise ValueError("reference_frame_by_modality must use the same modality labels as images_by_modality.")
    noise_variance_maps = {
        str(modality): _validated_image_array(str(modality), image)
        for modality, image in (noise_variance_by_modality or {}).items()
    }
    if noise_variance_maps and set(noise_variance_maps) != set(images):
        raise ValueError("noise_variance_by_modality must use the same modality labels as images_by_modality.")
    for modality, arr in rendered_signal_frames.items():
        if arr.shape != image_shape:
            raise ValueError(f"rendered_signal_frame for modality {modality!r} has shape {arr.shape}, expected {image_shape}.")
    for modality, arr in reference_frames.items():
        if arr.shape != image_shape:
            raise ValueError(f"reference_frame for modality {modality!r} has shape {arr.shape}, expected {image_shape}.")
    for modality, arr in noise_variance_maps.items():
        if arr.shape != image_shape:
            raise ValueError(f"noise_variance_map for modality {modality!r} has shape {arr.shape}, expected {image_shape}.")
        if np.any(arr <= 0.0):
            raise ValueError(f"noise_variance_map for modality {modality!r} must be positive.")

    fisher_arrays = {
        str(modality): np.asarray(fisher, dtype=float)
        for modality, fisher in (fisher_by_modality or {}).items()
    }
    missing_fisher_images = sorted(set(fisher_arrays) - set(images))
    if missing_fisher_images:
        raise ValueError(
            "fisher_by_modality contains labels not present in images_by_modality: "
            f"{missing_fisher_images!r}."
        )
    if fisher_arrays and set(fisher_arrays) != set(images):
        raise ValueError(
            "fisher_by_modality must use the same modality labels as images_by_modality."
        )
    for modality, fisher in fisher_arrays.items():
        if fisher.ndim != 2 or fisher.shape[0] != fisher.shape[1]:
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be square 2D; "
                f"got {fisher.shape}."
            )
        if np.any(~np.isfinite(fisher)):
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must contain only finite values."
            )
        if not np.allclose(fisher, fisher.T, rtol=1e-10, atol=1e-12):
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be symmetric."
            )
        eigvals = np.linalg.eigvalsh(0.5 * (fisher + fisher.T))
        eig_scale = max(float(np.max(np.abs(eigvals))) if eigvals.size else 0.0, 1.0)
        if float(np.min(eigvals)) < -1e-12 * eig_scale:
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be positive semidefinite."
            )

    crlb_metadata = {str(k): dict(v) for k, v in (crlb_by_modality or {}).items()}
    if crlb_metadata and set(crlb_metadata) != set(images):
        raise ValueError(
            "crlb_by_modality must use the same modality labels as images_by_modality."
        )
    if require_information_fields:
        if set(fisher_arrays) != set(images):
            raise ValueError(
                "Matched-modality information packets require a Fisher matrix for every modality."
            )
        if set(crlb_metadata) != set(images):
            raise ValueError(
                "Matched-modality information packets require CRLB metadata for every modality."
            )
        if set(rendered_signal_frames) != set(images):
            raise ValueError(
                "Matched-modality information packets require rendered signal frames for every modality."
            )
        if set(noise_variance_maps) != set(images):
            raise ValueError(
                "Matched-modality information packets require noise-variance maps for every modality."
            )
        mask_modalities = _mask_names_cover_modalities(set(mask_arrays), set(images))
        if mask_modalities != set(images):
            missing_masks = sorted(set(images) - mask_modalities)
            raise ValueError(
                "Matched-modality information packets require at least one supervision "
                f"mask array for every modality; missing {missing_masks!r}."
            )
        required_roles = set(_MATCHED_INFORMATION_MASK_ROLES)
        missing_roles = {
            modality: sorted(required_roles - _required_mask_roles_present(set(mask_arrays), modality))
            for modality in images
        }
        missing_roles = {modality: roles for modality, roles in missing_roles.items() if roles}
        if missing_roles:
            raise ValueError(
                "Matched-modality information packets require mask_geometry, "
                "mask_supported, ignore_mask, and loss_weight for every modality; "
                f"missing {missing_roles!r}."
            )
        _validate_matched_mask_semantics(mask_arrays, set(images))

    packet_extra_metadata = dict(metadata or {})
    if "shared_coordinate_frame" not in packet_extra_metadata:
        raise ValueError(
            "Counterfactual packets must include metadata['shared_coordinate_frame'] "
            "describing the common pixel/world/Fisher coordinate frame."
        )
    if require_information_fields:
        _validate_modality_profile_cards(packet_extra_metadata, set(images))

    packet_metadata = {
        "schema_version": (
            "syniscopy-matched-modality-packet-v1"
            if require_information_fields
            else "syniscopy-counterfactual-modality-packet-v1"
        ),
        "packet_kind": (
            "matched_modality_information_packet"
            if require_information_fields
            else "counterfactual_image_packet"
        ),
        "modalities": list(images.keys()),
        "image_key_to_modality": _safe_key_map(list(images.keys()), kind="modality"),
        "fisher_key_to_modality": _safe_key_map(list(fisher_arrays.keys()), kind="fisher"),
        "image_shape": list(image_shape),
        "image_contract": {
            "images_by_modality": "common_grid_reprojected_or_native_common_grid",
            "raw_images_by_modality": "optional_native_modality_grid",
        },
        "raw_image_shapes": {name: list(arr.shape) for name, arr in raw_images.items()},
        "rendered_signal_frame_shapes": {
            name: list(arr.shape) for name, arr in rendered_signal_frames.items()
        },
        "reference_frame_shapes": {
            name: list(arr.shape) for name, arr in reference_frames.items()
        },
        "noise_variance_map_shapes": {
            name: list(arr.shape) for name, arr in noise_variance_maps.items()
        },
        "latent_state": json_safe_with_nonfinite_tags(dict(latent_state), flexible_numpy=True),
        "has_fisher_by_modality": bool(fisher_arrays),
        "crlb_by_modality": json_safe_with_nonfinite_tags(crlb_metadata, flexible_numpy=True),
        "metadata": json_safe_with_nonfinite_tags(packet_extra_metadata, flexible_numpy=True),
        "masks": list(mask_arrays.keys()),
        "mask_key_to_name": _safe_key_map(list(mask_arrays.keys()), kind="mask"),
    }

    return {
        "metadata": packet_metadata,
        "images_by_modality": images,
        "fisher_by_modality": fisher_arrays,
        "masks": mask_arrays,
        "raw_images_by_modality": raw_images,
        "rendered_signal_frame_by_modality": rendered_signal_frames,
        "reference_frame_by_modality": reference_frames,
        "noise_variance_by_modality": noise_variance_maps,
    }


def save_counterfactual_modality_packet(
    path: str,
    *,
    latent_state: Mapping[str, Any],
    images_by_modality: Mapping[str, np.ndarray],
    masks: Mapping[str, np.ndarray] | None = None,
    raw_images_by_modality: Mapping[str, np.ndarray] | None = None,
    rendered_signal_frame_by_modality: Mapping[str, np.ndarray] | None = None,
    reference_frame_by_modality: Mapping[str, np.ndarray] | None = None,
    noise_variance_by_modality: Mapping[str, np.ndarray] | None = None,
    fisher_by_modality: Mapping[str, np.ndarray] | None = None,
    crlb_by_modality: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
    compressed: bool = True,
) -> str:
    """
    Save a counterfactual modality packet as ``.npz`` and return the path.
    """
    packet = build_counterfactual_modality_packet(
        latent_state=latent_state,
        images_by_modality=images_by_modality,
        masks=masks,
        raw_images_by_modality=raw_images_by_modality,
        rendered_signal_frame_by_modality=rendered_signal_frame_by_modality,
        reference_frame_by_modality=reference_frame_by_modality,
        noise_variance_by_modality=noise_variance_by_modality,
        fisher_by_modality=fisher_by_modality,
        crlb_by_modality=crlb_by_modality,
        metadata=metadata,
        require_information_fields=require_information_fields,
    )

    arrays: dict[str, Any] = {
        "metadata_json": np.array(
            json.dumps(packet["metadata"], sort_keys=True, allow_nan=False)
        )
    }
    for modality, image in packet["images_by_modality"].items():
        arrays[f"image__{_safe_key(modality)}"] = image
    for modality, image in packet["raw_images_by_modality"].items():
        arrays[f"raw_image__{_safe_key(modality)}"] = image
    for modality, image in packet["rendered_signal_frame_by_modality"].items():
        arrays[f"signal__{_safe_key(modality)}"] = image
    for modality, image in packet["reference_frame_by_modality"].items():
        arrays[f"reference__{_safe_key(modality)}"] = image
    for modality, image in packet["noise_variance_by_modality"].items():
        arrays[f"noise_variance__{_safe_key(modality)}"] = image
    for modality, fisher in packet["fisher_by_modality"].items():
        arrays[f"fisher__{_safe_key(modality)}"] = fisher
    for name, mask in packet["masks"].items():
        arrays[f"mask__{_safe_key(name)}"] = mask

    output_path = os.path.abspath(path)
    if not output_path.lower().endswith(".npz"):
        output_path += ".npz"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    if compressed:
        np.savez_compressed(output_path, **arrays)
    else:
        np.savez(output_path, **arrays)
    return output_path


def load_counterfactual_modality_packet(path: str) -> dict[str, Any]:
    """Load a packet saved by :func:`save_counterfactual_modality_packet`."""
    def _mapped_arrays(
        data: Any,
        *,
        prefix: str,
        key_map: Mapping[str, Any],
        map_name: str,
    ) -> dict[str, np.ndarray]:
        out: dict[str, np.ndarray] = {}
        for key in data.files:
            if not key.startswith(prefix):
                continue
            safe_key = key[len(prefix):]
            if safe_key not in key_map:
                raise ValueError(
                    f"Counterfactual packet metadata missing {map_name}[{safe_key!r}] "
                    f"for array key {key!r}."
                )
            out[str(key_map[safe_key])] = np.asarray(data[key])
        return out

    with np.load(path, allow_pickle=False) as data:
        metadata = json.loads(str(data["metadata_json"].item()))
        image_key_to_modality = metadata.get("image_key_to_modality", {})
        fisher_key_to_modality = metadata.get("fisher_key_to_modality", {})
        mask_key_to_name = metadata.get("mask_key_to_name", {})
        if not isinstance(image_key_to_modality, Mapping):
            raise ValueError("Counterfactual packet metadata field 'image_key_to_modality' must be a mapping.")
        if not isinstance(fisher_key_to_modality, Mapping):
            raise ValueError("Counterfactual packet metadata field 'fisher_key_to_modality' must be a mapping.")
        if not isinstance(mask_key_to_name, Mapping):
            raise ValueError("Counterfactual packet metadata field 'mask_key_to_name' must be a mapping.")
        images = _mapped_arrays(data, prefix="image__", key_map=image_key_to_modality, map_name="image_key_to_modality")
        fishers = _mapped_arrays(data, prefix="fisher__", key_map=fisher_key_to_modality, map_name="fisher_key_to_modality")
        masks = _mapped_arrays(data, prefix="mask__", key_map=mask_key_to_name, map_name="mask_key_to_name")
        raw_images = _mapped_arrays(data, prefix="raw_image__", key_map=image_key_to_modality, map_name="image_key_to_modality")
        rendered_signal_frames = _mapped_arrays(data, prefix="signal__", key_map=image_key_to_modality, map_name="image_key_to_modality")
        reference_frames = _mapped_arrays(data, prefix="reference__", key_map=image_key_to_modality, map_name="image_key_to_modality")
        noise_variance_maps = _mapped_arrays(data, prefix="noise_variance__", key_map=image_key_to_modality, map_name="image_key_to_modality")
    packet = {
        "metadata": metadata,
        "images_by_modality": images,
        "raw_images_by_modality": raw_images,
        "rendered_signal_frame_by_modality": rendered_signal_frames,
        "reference_frame_by_modality": reference_frames,
        "noise_variance_by_modality": noise_variance_maps,
        "fisher_by_modality": fishers,
        "masks": masks,
    }
    validate_counterfactual_modality_packet(packet)
    return packet


def validate_counterfactual_modality_packet(packet: Mapping[str, Any]) -> None:
    """Validate a loaded or in-memory counterfactual packet."""
    metadata = dict(packet.get("metadata", {}) or {})
    packet_extra = dict(metadata.get("metadata", {}) or {})
    build_counterfactual_modality_packet(
        latent_state=dict(metadata.get("latent_state", {}) or {}),
        images_by_modality=dict(packet.get("images_by_modality", {}) or {}),
        raw_images_by_modality=dict(packet.get("raw_images_by_modality", {}) or {}),
        rendered_signal_frame_by_modality=dict(packet.get("rendered_signal_frame_by_modality", {}) or {}),
        reference_frame_by_modality=dict(packet.get("reference_frame_by_modality", {}) or {}),
        noise_variance_by_modality=dict(packet.get("noise_variance_by_modality", {}) or {}),
        masks=dict(packet.get("masks", {}) or {}),
        fisher_by_modality=dict(packet.get("fisher_by_modality", {}) or {}),
        crlb_by_modality=dict(metadata.get("crlb_by_modality", {}) or {}),
        metadata=packet_extra,
        require_information_fields=metadata.get("packet_kind") == "matched_modality_information_packet",
    )
