"""
Counterfactual modality packet utilities.

A counterfactual packet stores one latent scene/trajectory state rendered under
multiple modalities. The file format is a portable ``.npz`` bundle containing:

    - ``metadata_json``: JSON with latent state, modality names, CRLB metadata,
      and annotation schema.
    - ``image__<modality>`` arrays: one image per selected modality.
    - ``fisher__<modality>`` arrays: Fisher matrices per modality when generated
      by the dataset packet workflow.
    - ``mask__<name>`` arrays: geometry/supported/ignore masks when generated by
      the dataset packet workflow.

Rendering is handled by the simulator/dataset workflow; this module owns the
portable packet contract and validation.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Mapping

import numpy as np


_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


def _safe_key(name: str) -> str:
    out = _SAFE_NAME_RE.sub("_", str(name).strip())
    return out.strip("_") or "unnamed"


def _json_safe(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    if isinstance(value, complex):
        return {
            "real": _json_safe(float(value.real)),
            "imag": _json_safe(float(value.imag)),
        }
    if hasattr(value, "tolist"):
        return _json_safe(value.tolist())
    if hasattr(value, "item"):
        try:
            return _json_safe(value.item())
        except (TypeError, ValueError, OverflowError):
            return value
    if isinstance(value, float):
        return value if np.isfinite(value) else None
    return value


def _safe_key_map(names: list[str], *, kind: str) -> dict[str, str]:
    """Map storage-safe keys back to original labels, rejecting collisions."""
    mapping: dict[str, str] = {}
    for name in names:
        safe = _safe_key(name)
        if safe in mapping and mapping[safe] != name:
            raise ValueError(
                f"Counterfactual packet {kind} labels {mapping[safe]!r} and "
                f"{name!r} both map to storage key {safe!r}."
            )
        mapping[safe] = name
    return mapping


def _mask_names_cover_modalities(mask_names: set[str], modalities: set[str]) -> set[str]:
    """Return modalities that have at least one modality-prefixed mask name."""
    covered: set[str] = set()
    for modality in modalities:
        prefix = f"{modality}__"
        safe_prefix = f"{_safe_key(modality)}__"
        if any(name == modality or name.startswith(prefix) or name.startswith(safe_prefix) for name in mask_names):
            covered.add(modality)
    return covered


def build_counterfactual_modality_packet(
    *,
    latent_state: Mapping[str, Any],
    images_by_modality: Mapping[str, np.ndarray],
    masks: Mapping[str, np.ndarray] | None = None,
    fisher_by_modality: Mapping[str, np.ndarray] | None = None,
    crlb_by_modality: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
) -> dict[str, Any]:
    """
    Build an in-memory counterfactual packet.

    Parameters
    ----------
    latent_state:
        Machine-readable description of the shared particle state, trajectory
        slice, seed, frame index, or other variables common to all modalities.
    images_by_modality:
        Mapping from modality label to rendered image. All images must share
        shape so they are valid counterfactual observations of the same scene.
    masks:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach supervision masks such as ``mask_geometry``,
        ``mask_supported``, and ``ignore_mask``.
    fisher_by_modality:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach per-modality Fisher matrices on the shared parameter
        frame.
    crlb_by_modality:
        Optional for the low-level builder. Dataset-generated matched-modality
        packets attach per-modality CRLB dictionaries.
    metadata:
        Optional additional packet-level metadata.
    require_information_fields:
        Require masks, Fisher matrices, and CRLB dictionaries for every modality.
        Dataset-generated matched-modality information packets enable this.
    """
    if len(images_by_modality) < 2:
        raise ValueError("images_by_modality must contain at least two modalities.")

    images = {
        str(modality): np.asarray(image)
        for modality, image in images_by_modality.items()
    }
    shapes = {image.shape for image in images.values()}
    if len(shapes) != 1:
        raise ValueError(
            "All modality images in a counterfactual packet must share shape; "
            f"got {sorted(shapes)!r}."
        )

    mask_arrays = {
        str(name): np.asarray(mask)
        for name, mask in (masks or {}).items()
    }
    image_shape = next(iter(shapes))
    for name, mask in mask_arrays.items():
        if mask.shape != image_shape:
            raise ValueError(
                f"Mask {name!r} has shape {mask.shape}, expected {image_shape}."
            )

    fisher_arrays = {
        str(modality): np.asarray(fisher, dtype=float)
        for modality, fisher in (fisher_by_modality or {}).items()
    }
    missing_fisher_images = sorted(set(fisher_arrays) - set(images))
    if missing_fisher_images:
        raise ValueError(
            "fisher_by_modality contains labels not present in images_by_modality: "
            f"{missing_fisher_images!r}."
        )
    if fisher_arrays and set(fisher_arrays) != set(images):
        raise ValueError(
            "fisher_by_modality must use the same modality labels as images_by_modality."
        )
    for modality, fisher in fisher_arrays.items():
        if fisher.ndim != 2 or fisher.shape[0] != fisher.shape[1]:
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be square 2D; "
                f"got {fisher.shape}."
            )
        if np.any(~np.isfinite(fisher)):
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must contain only finite values."
            )
        if not np.allclose(fisher, fisher.T, rtol=1e-10, atol=1e-12):
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be symmetric."
            )
        eigvals = np.linalg.eigvalsh(0.5 * (fisher + fisher.T))
        eig_scale = max(float(np.max(np.abs(eigvals))) if eigvals.size else 0.0, 1.0)
        if float(np.min(eigvals)) < -1e-12 * eig_scale:
            raise ValueError(
                f"Fisher matrix for modality {modality!r} must be positive semidefinite."
            )

    crlb_metadata = {str(k): dict(v) for k, v in (crlb_by_modality or {}).items()}
    if crlb_metadata and set(crlb_metadata) != set(images):
        raise ValueError(
            "crlb_by_modality must use the same modality labels as images_by_modality."
        )
    if require_information_fields:
        if set(fisher_arrays) != set(images):
            raise ValueError(
                "Matched-modality information packets require a Fisher matrix for every modality."
            )
        if set(crlb_metadata) != set(images):
            raise ValueError(
                "Matched-modality information packets require CRLB metadata for every modality."
            )
        mask_modalities = _mask_names_cover_modalities(set(mask_arrays), set(images))
        if mask_modalities != set(images):
            missing_masks = sorted(set(images) - mask_modalities)
            raise ValueError(
                "Matched-modality information packets require at least one supervision "
                f"mask array for every modality; missing {missing_masks!r}."
            )

    packet_extra_metadata = dict(metadata or {})
    if "shared_coordinate_frame" not in packet_extra_metadata:
        raise ValueError(
            "Counterfactual packets must include metadata['shared_coordinate_frame'] "
            "describing the common pixel/world/Fisher coordinate frame."
        )

    packet_metadata = {
        "schema_version": "syniscopy-counterfactual-modality-packet-v1",
        "packet_kind": (
            "matched_modality_information_packet"
            if require_information_fields
            else "counterfactual_image_packet"
        ),
        "modalities": list(images.keys()),
        "image_key_to_modality": _safe_key_map(list(images.keys()), kind="modality"),
        "fisher_key_to_modality": _safe_key_map(list(fisher_arrays.keys()), kind="fisher"),
        "image_shape": list(image_shape),
        "latent_state": _json_safe(dict(latent_state)),
        "has_fisher_by_modality": bool(fisher_arrays),
        "crlb_by_modality": _json_safe(crlb_metadata),
        "metadata": _json_safe(packet_extra_metadata),
        "masks": list(mask_arrays.keys()),
        "mask_key_to_name": _safe_key_map(list(mask_arrays.keys()), kind="mask"),
    }

    return {
        "metadata": packet_metadata,
        "images_by_modality": images,
        "fisher_by_modality": fisher_arrays,
        "masks": mask_arrays,
    }


def save_counterfactual_modality_packet(
    path: str,
    *,
    latent_state: Mapping[str, Any],
    images_by_modality: Mapping[str, np.ndarray],
    masks: Mapping[str, np.ndarray] | None = None,
    fisher_by_modality: Mapping[str, np.ndarray] | None = None,
    crlb_by_modality: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
    compressed: bool = True,
) -> str:
    """
    Save a counterfactual modality packet as ``.npz`` and return the path.
    """
    packet = build_counterfactual_modality_packet(
        latent_state=latent_state,
        images_by_modality=images_by_modality,
        masks=masks,
        fisher_by_modality=fisher_by_modality,
        crlb_by_modality=crlb_by_modality,
        metadata=metadata,
        require_information_fields=require_information_fields,
    )

    arrays: dict[str, Any] = {
        "metadata_json": np.array(
            json.dumps(packet["metadata"], sort_keys=True, allow_nan=False)
        )
    }
    for modality, image in packet["images_by_modality"].items():
        arrays[f"image__{_safe_key(modality)}"] = image
    for modality, fisher in packet["fisher_by_modality"].items():
        arrays[f"fisher__{_safe_key(modality)}"] = fisher
    for name, mask in packet["masks"].items():
        arrays[f"mask__{_safe_key(name)}"] = mask

    output_path = os.path.abspath(path)
    if not output_path.lower().endswith(".npz"):
        output_path += ".npz"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    if compressed:
        np.savez_compressed(output_path, **arrays)
    else:
        np.savez(output_path, **arrays)
    return output_path


def load_counterfactual_modality_packet(path: str) -> dict[str, Any]:
    """Load a packet saved by :func:`save_counterfactual_modality_packet`."""
    with np.load(path, allow_pickle=False) as data:
        metadata = json.loads(str(data["metadata_json"].item()))
        image_key_to_modality = metadata.get("image_key_to_modality", {})
        fisher_key_to_modality = metadata.get("fisher_key_to_modality", {})
        mask_key_to_name = metadata.get("mask_key_to_name", {})
        images = {
            image_key_to_modality.get(key[len("image__"):], key[len("image__"):]): np.asarray(data[key])
            for key in data.files
            if key.startswith("image__")
        }
        fishers = {
            fisher_key_to_modality.get(key[len("fisher__"):], key[len("fisher__"):]): np.asarray(data[key])
            for key in data.files
            if key.startswith("fisher__")
        }
        masks = {
            mask_key_to_name.get(key[len("mask__"):], key[len("mask__"):]): np.asarray(data[key])
            for key in data.files
            if key.startswith("mask__")
        }
    return {
        "metadata": metadata,
        "images_by_modality": images,
        "fisher_by_modality": fishers,
        "masks": masks,
    }
