"""
Matched microscope packet utilities.

A matched packet stores one latent scene/trajectory state rendered under
multiple configured microscopes. A microscope is the comparison identity; its
contrast modality is backend metadata. The file format is a portable ``.npz``
bundle containing:

    - ``metadata_json``: JSON with latent state, microscope names, modality
      metadata, CRLB metadata, and annotation schema.
    - ``image__<microscope>`` arrays: one image per selected microscope.
    - ``fisher__<microscope>`` arrays: Fisher matrices per microscope when
      generated by the dataset packet workflow.
    - ``mask__<name>`` arrays: geometry/supported/ignore masks when generated by
      the dataset packet workflow.

Rendering is handled by the simulator/dataset workflow; this module owns the
portable packet contract and validation.
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Mapping

import numpy as np
from json_utils import json_safe_with_nonfinite_tags
from modality_registry import require_modality_name
from noise_contracts import (
    AnalysisNoiseModel,
    analysis_noise_model_from_likelihood,
    analysis_noise_model_to_likelihood,
)
from shared_constants import MATCHED_INFORMATION_MASK_ROLES
from packet_validation import _validate_profile_card_contract


_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_.-]+")


def _safe_key(name: str) -> str:
    out = _SAFE_NAME_RE.sub("_", str(name).strip())
    return out.strip("_") or "unnamed"


def _validated_image_array(label: str, image: Any) -> np.ndarray:
    arr = np.asarray(image)
    if arr.ndim < 2:
        raise ValueError(f"Image for microscope {label!r} must be at least 2D; got {arr.shape}.")
    if arr.dtype == object or not np.issubdtype(arr.dtype, np.number):
        raise ValueError(f"Image for microscope {label!r} must have a numeric non-object dtype; got {arr.dtype}.")
    if np.iscomplexobj(arr):
        raise ValueError(f"Image for microscope {label!r} must be real-valued, not complex.")
    arr = np.asarray(arr, dtype=float)
    if np.any(~np.isfinite(arr)):
        raise ValueError(f"Image for microscope {label!r} must contain only finite values.")
    return arr


def _validated_mask_array(name: str, mask: Any, image_shape: tuple[int, ...]) -> np.ndarray:
    arr = np.asarray(mask)
    if arr.shape != image_shape:
        raise ValueError(f"Mask {name!r} has shape {arr.shape}, expected {image_shape}.")
    if arr.dtype == object or not (np.issubdtype(arr.dtype, np.bool_) or np.issubdtype(arr.dtype, np.number)):
        raise ValueError(f"Mask {name!r} must have boolean or numeric dtype; got {arr.dtype}.")
    if np.iscomplexobj(arr):
        raise ValueError(f"Mask {name!r} must be real-valued, not complex.")
    numeric = np.asarray(arr)
    if np.any(~np.isfinite(numeric.astype(float, copy=False))):
        raise ValueError(f"Mask {name!r} must contain only finite values.")
    values = np.unique(numeric)
    if "loss_weight" in name:
        if np.any(values < 0) or np.any(values > 255):
            raise ValueError(f"Loss-weight mask {name!r} must lie in [0, 255].")
        return numeric.astype(np.uint8, copy=False)
    if not np.all(np.isin(values, [0, 1, 255, False, True])):
        raise ValueError(f"Mask {name!r} must be binary/bool with values 0/1 or 0/255; got values {values[:8]!r}.")
    return np.where(numeric.astype(float, copy=False) > 0.0, 255, 0).astype(np.uint8)


def _safe_key_map(names: list[str], *, kind: str) -> dict[str, str]:
    """Map storage-safe keys back to original labels, rejecting collisions."""
    mapping: dict[str, str] = {}
    for name in names:
        safe = _safe_key(name)
        if safe in mapping and mapping[safe] != name:
            raise ValueError(
                f"Matched microscope packet {kind} labels {mapping[safe]!r} and "
                f"{name!r} both map to storage key {safe!r}."
            )
        mapping[safe] = name
    return mapping


def _mask_names_cover_microscopes(mask_names: set[str], microscopes: set[str]) -> set[str]:
    """Return microscopes that have at least one microscope-prefixed mask name."""
    covered: set[str] = set()
    for microscope in microscopes:
        prefix = f"{microscope}__"
        safe_prefix = f"{_safe_key(microscope)}__"
        if any(name == microscope or name.startswith(prefix) or name.startswith(safe_prefix) for name in mask_names):
            covered.add(microscope)
    return covered


_MATCHED_INFORMATION_MASK_ROLES = MATCHED_INFORMATION_MASK_ROLES


def _validated_modality_by_microscope(
    modality_by_microscope: Mapping[str, Any],
    *,
    microscope_names: set[str],
) -> dict[str, str]:
    """Validate microscope -> modality metadata without making modality identity."""

    if not isinstance(modality_by_microscope, Mapping):
        raise ValueError(
            "modality_by_microscope is required. Matched packets cannot infer "
            "a modality from the microscope name because same-modality "
            "microscopes are valid distinct candidates."
        )
    mapping = {}
    for name, modality in modality_by_microscope.items():
        microscope = str(name)
        mapping[microscope] = require_modality_name(
            modality,
            item_label=f"modality_by_microscope[{microscope!r}]",
        )
    if set(mapping) != set(microscope_names):
        missing = sorted(set(microscope_names) - set(mapping))
        extra = sorted(set(mapping) - set(microscope_names))
        raise ValueError(
            "modality_by_microscope must use the same microscope labels as "
            f"images_by_microscope; missing={missing!r}, extra={extra!r}."
        )
    return mapping


def _required_mask_roles_present(mask_names: set[str], microscope: str) -> set[str]:
    roles = set()
    prefixes = (f"{microscope}__", f"{_safe_key(microscope)}__")
    for name in mask_names:
        for prefix in prefixes:
            if not name.startswith(prefix):
                continue
            remainder = name[len(prefix):]
            for role in _MATCHED_INFORMATION_MASK_ROLES:
                if remainder == role or remainder.startswith(f"{role}__"):
                    roles.add(role)
    return roles


def _mask_role_and_suffix(name: str, microscope: str) -> tuple[str, str] | None:
    prefixes = (f"{microscope}__", f"{_safe_key(microscope)}__")
    for prefix in prefixes:
        if not name.startswith(prefix):
            continue
        remainder = name[len(prefix):]
        for role in _MATCHED_INFORMATION_MASK_ROLES:
            if remainder == role:
                return role, ""
            if remainder.startswith(f"{role}__"):
                return role, remainder[len(role) + 2:]
    return None


def _validate_matched_mask_semantics(
    mask_arrays: Mapping[str, np.ndarray],
    microscopes: set[str],
) -> None:
    """Validate semantic invariants across per-particle supervision sidecars."""
    for microscope in sorted(microscopes):
        grouped: dict[str, dict[str, np.ndarray]] = {}
        for name, arr in mask_arrays.items():
            parsed = _mask_role_and_suffix(str(name), microscope)
            if parsed is None:
                continue
            role, suffix = parsed
            grouped.setdefault(suffix, {})[role] = np.asarray(arr)
        for suffix, roles in grouped.items():
            missing = set(_MATCHED_INFORMATION_MASK_ROLES) - set(roles)
            if missing:
                continue
            label = f"{microscope}::{suffix or 'default'}"
            geometry = np.asarray(roles["mask_geometry"]) > 0
            supported = np.asarray(roles["mask_supported"]) > 0
            ignored = np.asarray(roles["ignore_mask"]) > 0
            loss_weight = np.asarray(roles["loss_weight"], dtype=float)
            if np.any(supported & ~geometry):
                raise ValueError(
                    f"Matched packet masks for {label} violate mask_supported subset mask_geometry."
                )
            if np.any(ignored & ~geometry):
                raise ValueError(
                    f"Matched packet masks for {label} violate ignore_mask subset mask_geometry."
                )
            expected_ignore = geometry & ~supported
            if not np.array_equal(ignored, expected_ignore):
                raise ValueError(
                    f"Matched packet masks for {label} violate ignore_mask == mask_geometry & ~mask_supported."
                )
            if np.any(loss_weight[~supported] > 0.0):
                raise ValueError(
                    f"Matched packet masks for {label} have positive loss_weight outside mask_supported."
                )
            if np.any(supported) and not np.any(loss_weight[supported] > 0.0):
                raise ValueError(
                    f"Matched packet masks for {label} have supported pixels but no positive loss_weight."
                )


def _validate_microscope_profile_cards(
    packet_metadata: Mapping[str, Any],
    microscopes: set[str],
    *,
    modality_by_microscope: Mapping[str, str],
) -> None:
    microscope_metadata = packet_metadata.get("microscope_metadata")
    if not isinstance(microscope_metadata, Mapping):
        raise ValueError(
            "Matched microscope information packets require "
            "metadata['microscope_metadata']."
        )
    missing_records = sorted(microscopes - {str(key) for key in microscope_metadata})
    if missing_records:
        raise ValueError(
            "Matched microscope information packets require microscope metadata "
            f"for every microscope; missing {missing_records!r}."
        )
    for microscope in sorted(microscopes):
        record = microscope_metadata.get(microscope)
        if not isinstance(record, Mapping):
            raise ValueError(
                f"metadata['microscope_metadata'][{microscope!r}] must be a mapping."
            )
        card = record.get("modality_profile_card")
        if not isinstance(card, Mapping):
            raise ValueError(
                f"Microscope {microscope!r} is missing modality_profile_card metadata."
            )
        _validate_profile_card_contract(modality_by_microscope[microscope], card)


def _validate_information_packet_frame_basis(
    packet_metadata: Mapping[str, Any],
    microscopes: set[str],
) -> None:
    signal_basis_by_microscope = packet_metadata.get(
        "rendered_signal_frame_basis_by_microscope",
    )
    reference_basis_by_microscope = packet_metadata.get(
        "reference_frame_basis_by_microscope",
    )
    if not isinstance(signal_basis_by_microscope, Mapping):
        raise ValueError(
            "Matched microscope information packets require "
            "metadata['rendered_signal_frame_basis_by_microscope']."
        )
    if not isinstance(reference_basis_by_microscope, Mapping):
        raise ValueError(
            "Matched microscope information packets require "
            "metadata['reference_frame_basis_by_microscope']."
        )
    valid_bases = {
        "detector_mean_before_stochastic_noise",
        "phase_or_display_signal_before_detector_count_mean_transfer",
    }
    missing_signal = sorted(microscopes - {str(key) for key in signal_basis_by_microscope})
    missing_reference = sorted(microscopes - {str(key) for key in reference_basis_by_microscope})
    if missing_signal or missing_reference:
        raise ValueError(
            "Matched microscope information packets require signal/reference frame "
            "basis metadata for every microscope; missing "
            f"signal={missing_signal!r}, reference={missing_reference!r}."
        )
    for microscope in sorted(microscopes):
        signal_basis = str(signal_basis_by_microscope[microscope])
        reference_basis = str(reference_basis_by_microscope[microscope])
        if signal_basis not in valid_bases:
            raise ValueError(
                f"Microscope {microscope!r} has unsupported rendered signal frame basis "
                f"{signal_basis!r}."
            )
        if reference_basis not in valid_bases:
            raise ValueError(
                f"Microscope {microscope!r} has unsupported reference frame basis "
                f"{reference_basis!r}."
            )
        if signal_basis != reference_basis:
            raise ValueError(
                f"Microscope {microscope!r} signal/reference frame bases differ: "
                f"{signal_basis!r} vs {reference_basis!r}."
            )


def _analysis_noise_metadata_for_packet(model: AnalysisNoiseModel) -> dict[str, Any]:
    """Return JSON metadata for a likelihood whose large arrays are in NPZ."""
    couplings = model.row_correlated_couplings
    return {
        "schema_version": "syniscopy-analysis-noise-likelihood-v1",
        "diagonal_variance_shape": list(np.asarray(model.diagonal_variance, dtype=float).shape),
        "measurement_domain": str(model.measurement_domain),
        "signal_units": str(model.signal_units),
        "noise_variance_units": str(model.noise_variance_units),
        "covariance_kind": str(model.covariance_kind),
        "row_correlated_variance": float(model.row_correlated_variance),
        "row_correlated_component_variances": [
            float(v) for v in model.row_correlated_component_variances
        ],
        "row_correlated_couplings_shape": (
            None if couplings is None else list(np.asarray(couplings, dtype=float).shape)
        ),
        "safe_for_ordering": bool(model.safe_for_ordering),
        "safe_for_fusion": bool(model.safe_for_fusion),
        "status_reason": str(model.status_reason),
    }


def _validated_analysis_noise_models(
    analysis_noise_model_by_microscope: Mapping[str, Any] | None,
    *,
    images: Mapping[str, np.ndarray],
    image_shape: tuple[int, ...],
    context: str,
) -> dict[str, AnalysisNoiseModel]:
    models: dict[str, AnalysisNoiseModel] = {}
    for microscope, payload in (analysis_noise_model_by_microscope or {}).items():
        label = str(microscope)
        model = analysis_noise_model_from_likelihood(
            payload,
            context=f"{context} analysis_noise_model_by_microscope[{label!r}]",
        )
        variance = np.asarray(model.diagonal_variance, dtype=float)
        if variance.shape != image_shape:
            raise ValueError(
                f"analysis_noise_model for microscope {label!r} has diagonal_variance "
                f"shape {variance.shape}, expected {image_shape}."
            )
        # Re-serialize through the shared contract so packet validation and
        # Fisher consumers agree on units, covariance kind, and row couplings.
        models[label] = analysis_noise_model_from_likelihood(
            analysis_noise_model_to_likelihood(model),
            context=f"{context} normalized analysis_noise_model_by_microscope[{label!r}]",
        )
    if models and set(models) != set(images):
        raise ValueError(
            "analysis_noise_model_by_microscope must use the same microscope "
            "labels as images_by_microscope."
        )
    return models


MATCHED_MICROSCOPE_PACKET_SCHEMA_VERSION = "syniscopy-matched-microscope-packet-v2"
MATCHED_MICROSCOPE_IMAGE_PACKET_SCHEMA_VERSION = "syniscopy-matched-microscope-image-packet-v1"
MATCHED_MICROSCOPE_PACKET_KIND = "matched_microscope_information_packet"
MATCHED_MICROSCOPE_IMAGE_PACKET_KIND = "matched_microscope_image_packet"


def build_matched_microscope_packet(
    *,
    latent_state: Mapping[str, Any],
    images_by_microscope: Mapping[str, np.ndarray],
    modality_by_microscope: Mapping[str, Any],
    masks: Mapping[str, np.ndarray] | None = None,
    raw_images_by_microscope: Mapping[str, np.ndarray] | None = None,
    rendered_signal_frame_by_microscope: Mapping[str, np.ndarray] | None = None,
    reference_frame_by_microscope: Mapping[str, np.ndarray] | None = None,
    noise_variance_by_microscope: Mapping[str, np.ndarray] | None = None,
    analysis_noise_model_by_microscope: Mapping[str, Any] | None = None,
    fisher_by_microscope: Mapping[str, np.ndarray] | None = None,
    crlb_by_microscope: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
) -> dict[str, Any]:
    """Build an in-memory matched microscope packet."""

    if len(images_by_microscope) < 2:
        raise ValueError("images_by_microscope must contain at least two microscopes.")

    images = {
        str(microscope): _validated_image_array(str(microscope), image)
        for microscope, image in images_by_microscope.items()
    }
    microscope_names = set(images)
    modality_map = _validated_modality_by_microscope(
        modality_by_microscope,
        microscope_names=microscope_names,
    )
    shapes = {image.shape for image in images.values()}
    if len(shapes) != 1:
        raise ValueError(
            "All microscope images in a matched packet must share shape; "
            f"got {sorted(shapes)!r}."
        )

    image_shape = next(iter(shapes))
    mask_arrays = {
        str(name): _validated_mask_array(str(name), mask, image_shape)
        for name, mask in (masks or {}).items()
    }
    raw_images = {
        str(microscope): _validated_image_array(str(microscope), image)
        for microscope, image in (raw_images_by_microscope or {}).items()
    }
    if raw_images and set(raw_images) != set(images):
        raise ValueError("raw_images_by_microscope must use the same microscope labels as images_by_microscope.")
    rendered_signal_frames = {
        str(microscope): _validated_image_array(str(microscope), image)
        for microscope, image in (rendered_signal_frame_by_microscope or {}).items()
    }
    if rendered_signal_frames and set(rendered_signal_frames) != set(images):
        raise ValueError("rendered_signal_frame_by_microscope must use the same microscope labels as images_by_microscope.")
    reference_frames = {
        str(microscope): _validated_image_array(str(microscope), image)
        for microscope, image in (reference_frame_by_microscope or {}).items()
    }
    if reference_frames and set(reference_frames) != set(images):
        raise ValueError("reference_frame_by_microscope must use the same microscope labels as images_by_microscope.")
    noise_variance_maps = {
        str(microscope): _validated_image_array(str(microscope), image)
        for microscope, image in (noise_variance_by_microscope or {}).items()
    }
    if noise_variance_maps and set(noise_variance_maps) != set(images):
        raise ValueError("noise_variance_by_microscope must use the same microscope labels as images_by_microscope.")
    for microscope, arr in rendered_signal_frames.items():
        if arr.shape != image_shape:
            raise ValueError(f"rendered_signal_frame for microscope {microscope!r} has shape {arr.shape}, expected {image_shape}.")
    for microscope, arr in reference_frames.items():
        if arr.shape != image_shape:
            raise ValueError(f"reference_frame for microscope {microscope!r} has shape {arr.shape}, expected {image_shape}.")
    for microscope, arr in noise_variance_maps.items():
        if arr.shape != image_shape:
            raise ValueError(f"noise_variance_map for microscope {microscope!r} has shape {arr.shape}, expected {image_shape}.")
        if np.any(arr <= 0.0):
            raise ValueError(f"noise_variance_map for microscope {microscope!r} must be positive.")

    analysis_noise_models = _validated_analysis_noise_models(
        analysis_noise_model_by_microscope,
        images=images,
        image_shape=image_shape,
        context="matched microscope packet",
    )

    fisher_arrays = {
        str(microscope): np.asarray(fisher, dtype=float)
        for microscope, fisher in (fisher_by_microscope or {}).items()
    }
    missing_fisher_images = sorted(set(fisher_arrays) - set(images))
    if missing_fisher_images:
        raise ValueError(
            "fisher_by_microscope contains labels not present in images_by_microscope: "
            f"{missing_fisher_images!r}."
        )
    if fisher_arrays and set(fisher_arrays) != set(images):
        raise ValueError(
            "fisher_by_microscope must use the same microscope labels as images_by_microscope."
        )
    for microscope, fisher in fisher_arrays.items():
        if fisher.ndim != 2 or fisher.shape[0] != fisher.shape[1]:
            raise ValueError(
                f"Fisher matrix for microscope {microscope!r} must be square 2D; "
                f"got {fisher.shape}."
            )
        if np.any(~np.isfinite(fisher)):
            raise ValueError(
                f"Fisher matrix for microscope {microscope!r} must contain only finite values."
            )
        if not np.allclose(fisher, fisher.T, rtol=1e-10, atol=1e-12):
            raise ValueError(
                f"Fisher matrix for microscope {microscope!r} must be symmetric."
            )
        eigvals = np.linalg.eigvalsh(0.5 * (fisher + fisher.T))
        eig_scale = max(float(np.max(np.abs(eigvals))) if eigvals.size else 0.0, 1.0)
        if float(np.min(eigvals)) < -1e-12 * eig_scale:
            raise ValueError(
                f"Fisher matrix for microscope {microscope!r} must be positive semidefinite."
            )

    crlb_metadata = {str(k): dict(v) for k, v in (crlb_by_microscope or {}).items()}
    if crlb_metadata and set(crlb_metadata) != set(images):
        raise ValueError(
            "crlb_by_microscope must use the same microscope labels as images_by_microscope."
        )
    if require_information_fields:
        if set(fisher_arrays) != set(images):
            raise ValueError(
                "Matched microscope information packets require a Fisher matrix for every microscope."
            )
        if set(crlb_metadata) != set(images):
            raise ValueError(
                "Matched microscope information packets require CRLB metadata for every microscope."
            )
        if set(rendered_signal_frames) != set(images):
            raise ValueError(
                "Matched microscope information packets require rendered signal frames for every microscope."
            )
        if set(noise_variance_maps) != set(images):
            raise ValueError(
                "Matched microscope information packets require noise-variance maps for every microscope."
            )
        if set(analysis_noise_models) != set(images):
            raise ValueError(
                "Matched microscope information packets require a full analysis-noise "
                "likelihood for every microscope. noise_variance_by_microscope is only "
                "a diagonal summary and cannot represent row-correlated detector covariance."
            )
        mask_microscopes = _mask_names_cover_microscopes(set(mask_arrays), set(images))
        if mask_microscopes != set(images):
            missing_masks = sorted(set(images) - mask_microscopes)
            raise ValueError(
                "Matched microscope information packets require at least one supervision "
                f"mask array for every microscope; missing {missing_masks!r}."
            )
        required_roles = set(_MATCHED_INFORMATION_MASK_ROLES)
        missing_roles = {
            microscope: sorted(required_roles - _required_mask_roles_present(set(mask_arrays), microscope))
            for microscope in images
        }
        missing_roles = {microscope: roles for microscope, roles in missing_roles.items() if roles}
        if missing_roles:
            raise ValueError(
                "Matched microscope information packets require mask_geometry, "
                "mask_supported, ignore_mask, and loss_weight for every microscope; "
                f"missing {missing_roles!r}."
            )
        _validate_matched_mask_semantics(mask_arrays, set(images))

    packet_extra_metadata = dict(metadata or {})
    if "shared_coordinate_frame" not in packet_extra_metadata:
        raise ValueError(
            "Matched microscope packets must include metadata['shared_coordinate_frame'] "
            "describing the common pixel/world/Fisher coordinate frame."
        )
    if require_information_fields:
        _validate_microscope_profile_cards(
            packet_extra_metadata,
            set(images),
            modality_by_microscope=modality_map,
        )
        _validate_information_packet_frame_basis(packet_extra_metadata, set(images))

    packet_metadata = {
        "schema_version": (
            MATCHED_MICROSCOPE_PACKET_SCHEMA_VERSION
            if require_information_fields
            else MATCHED_MICROSCOPE_IMAGE_PACKET_SCHEMA_VERSION
        ),
        "packet_kind": (
            MATCHED_MICROSCOPE_PACKET_KIND
            if require_information_fields
            else MATCHED_MICROSCOPE_IMAGE_PACKET_KIND
        ),
        "comparison_unit": "microscope",
        "microscopes": list(images.keys()),
        "modality_by_microscope": json_safe_with_nonfinite_tags(
            modality_map,
            flexible_numpy=True,
        ),
        "image_key_to_microscope": _safe_key_map(list(images.keys()), kind="microscope"),
        "fisher_key_to_microscope": _safe_key_map(list(fisher_arrays.keys()), kind="fisher"),
        "image_shape": list(image_shape),
        "image_contract": {
            "images_by_microscope": "common_grid_reprojected_or_native_common_grid",
            "raw_images_by_microscope": "optional_native_microscope_grid",
            "rendered_signal_frame_by_microscope": "per_microscope_basis_declared_in_metadata",
            "reference_frame_by_microscope": "per_microscope_basis_declared_in_metadata",
        },
        "raw_image_shapes": {name: list(arr.shape) for name, arr in raw_images.items()},
        "rendered_signal_frame_shapes": {
            name: list(arr.shape) for name, arr in rendered_signal_frames.items()
        },
        "reference_frame_shapes": {
            name: list(arr.shape) for name, arr in reference_frames.items()
        },
        "noise_variance_map_shapes": {
            name: list(arr.shape) for name, arr in noise_variance_maps.items()
        },
        "analysis_noise_model_metadata_by_microscope": {
            name: _analysis_noise_metadata_for_packet(model)
            for name, model in analysis_noise_models.items()
        },
        "latent_state": json_safe_with_nonfinite_tags(dict(latent_state), flexible_numpy=True),
        "has_fisher_by_microscope": bool(fisher_arrays),
        "crlb_by_microscope": json_safe_with_nonfinite_tags(crlb_metadata, flexible_numpy=True),
        "metadata": json_safe_with_nonfinite_tags(packet_extra_metadata, flexible_numpy=True),
        "masks": list(mask_arrays.keys()),
        "mask_key_to_name": _safe_key_map(list(mask_arrays.keys()), kind="mask"),
    }

    return {
        "metadata": packet_metadata,
        "images_by_microscope": images,
        "fisher_by_microscope": fisher_arrays,
        "crlb_by_microscope": crlb_metadata,
        "masks": mask_arrays,
        "raw_images_by_microscope": raw_images,
        "rendered_signal_frame_by_microscope": rendered_signal_frames,
        "reference_frame_by_microscope": reference_frames,
        "noise_variance_by_microscope": noise_variance_maps,
        "analysis_noise_model_by_microscope": analysis_noise_models,
    }


def save_matched_microscope_packet(
    path: str,
    *,
    latent_state: Mapping[str, Any],
    images_by_microscope: Mapping[str, np.ndarray],
    modality_by_microscope: Mapping[str, Any],
    masks: Mapping[str, np.ndarray] | None = None,
    raw_images_by_microscope: Mapping[str, np.ndarray] | None = None,
    rendered_signal_frame_by_microscope: Mapping[str, np.ndarray] | None = None,
    reference_frame_by_microscope: Mapping[str, np.ndarray] | None = None,
    noise_variance_by_microscope: Mapping[str, np.ndarray] | None = None,
    analysis_noise_model_by_microscope: Mapping[str, Any] | None = None,
    fisher_by_microscope: Mapping[str, np.ndarray] | None = None,
    crlb_by_microscope: Mapping[str, Mapping[str, Any]] | None = None,
    metadata: Mapping[str, Any] | None = None,
    require_information_fields: bool = False,
    compressed: bool = True,
) -> str:
    """Save a matched microscope packet as ``.npz`` and return the path."""

    packet = build_matched_microscope_packet(
        latent_state=latent_state,
        images_by_microscope=images_by_microscope,
        modality_by_microscope=modality_by_microscope,
        masks=masks,
        raw_images_by_microscope=raw_images_by_microscope,
        rendered_signal_frame_by_microscope=rendered_signal_frame_by_microscope,
        reference_frame_by_microscope=reference_frame_by_microscope,
        noise_variance_by_microscope=noise_variance_by_microscope,
        analysis_noise_model_by_microscope=analysis_noise_model_by_microscope,
        fisher_by_microscope=fisher_by_microscope,
        crlb_by_microscope=crlb_by_microscope,
        metadata=metadata,
        require_information_fields=require_information_fields,
    )

    arrays: dict[str, Any] = {
        "metadata_json": np.array(
            json.dumps(packet["metadata"], sort_keys=True, allow_nan=False)
        )
    }
    for microscope, image in packet["images_by_microscope"].items():
        arrays[f"image__{_safe_key(microscope)}"] = image
    for microscope, image in packet["raw_images_by_microscope"].items():
        arrays[f"raw_image__{_safe_key(microscope)}"] = image
    for microscope, image in packet["rendered_signal_frame_by_microscope"].items():
        arrays[f"signal__{_safe_key(microscope)}"] = image
    for microscope, image in packet["reference_frame_by_microscope"].items():
        arrays[f"reference__{_safe_key(microscope)}"] = image
    for microscope, image in packet["noise_variance_by_microscope"].items():
        arrays[f"noise_variance__{_safe_key(microscope)}"] = image
    for microscope, model in packet["analysis_noise_model_by_microscope"].items():
        safe_microscope = _safe_key(microscope)
        arrays[f"analysis_noise_diagonal_variance__{safe_microscope}"] = np.asarray(
            model.diagonal_variance,
            dtype=float,
        )
        if model.row_correlated_couplings is not None:
            arrays[f"analysis_noise_row_couplings__{safe_microscope}"] = np.asarray(
                model.row_correlated_couplings,
                dtype=float,
            )
    for microscope, fisher in packet["fisher_by_microscope"].items():
        arrays[f"fisher__{_safe_key(microscope)}"] = fisher
    for name, mask in packet["masks"].items():
        arrays[f"mask__{_safe_key(name)}"] = mask

    output_path = os.path.abspath(path)
    if not output_path.lower().endswith(".npz"):
        output_path += ".npz"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    if compressed:
        np.savez_compressed(output_path, **arrays)
    else:
        np.savez(output_path, **arrays)
    return output_path


def load_matched_microscope_packet(path: str) -> dict[str, Any]:
    """Load a packet saved by :func:`save_matched_microscope_packet`."""

    def _mapped_arrays(
        data: Any,
        *,
        prefix: str,
        key_map: Mapping[str, Any],
        map_name: str,
    ) -> dict[str, np.ndarray]:
        out: dict[str, np.ndarray] = {}
        for key in data.files:
            if not key.startswith(prefix):
                continue
            safe_key = key[len(prefix):]
            if safe_key not in key_map:
                raise ValueError(
                    f"Matched microscope packet metadata missing {map_name}[{safe_key!r}] "
                    f"for array key {key!r}."
                )
            out[str(key_map[safe_key])] = np.asarray(data[key])
        return out

    with np.load(path, allow_pickle=False) as data:
        metadata = json.loads(str(data["metadata_json"].item()))
        image_key_to_microscope = metadata.get("image_key_to_microscope", {})
        fisher_key_to_microscope = metadata.get("fisher_key_to_microscope", {})
        mask_key_to_name = metadata.get("mask_key_to_name", {})
        if not isinstance(image_key_to_microscope, Mapping):
            raise ValueError("Matched microscope packet metadata field 'image_key_to_microscope' must be a mapping.")
        if not isinstance(fisher_key_to_microscope, Mapping):
            raise ValueError("Matched microscope packet metadata field 'fisher_key_to_microscope' must be a mapping.")
        if not isinstance(mask_key_to_name, Mapping):
            raise ValueError("Matched microscope packet metadata field 'mask_key_to_name' must be a mapping.")
        images = _mapped_arrays(data, prefix="image__", key_map=image_key_to_microscope, map_name="image_key_to_microscope")
        fishers = _mapped_arrays(data, prefix="fisher__", key_map=fisher_key_to_microscope, map_name="fisher_key_to_microscope")
        masks = _mapped_arrays(data, prefix="mask__", key_map=mask_key_to_name, map_name="mask_key_to_name")
        raw_images = _mapped_arrays(data, prefix="raw_image__", key_map=image_key_to_microscope, map_name="image_key_to_microscope")
        rendered_signal_frames = _mapped_arrays(data, prefix="signal__", key_map=image_key_to_microscope, map_name="image_key_to_microscope")
        reference_frames = _mapped_arrays(data, prefix="reference__", key_map=image_key_to_microscope, map_name="image_key_to_microscope")
        noise_variance_maps = _mapped_arrays(data, prefix="noise_variance__", key_map=image_key_to_microscope, map_name="image_key_to_microscope")
        analysis_noise_diagonal = _mapped_arrays(
            data,
            prefix="analysis_noise_diagonal_variance__",
            key_map=image_key_to_microscope,
            map_name="image_key_to_microscope",
        )
        analysis_noise_couplings = _mapped_arrays(
            data,
            prefix="analysis_noise_row_couplings__",
            key_map=image_key_to_microscope,
            map_name="image_key_to_microscope",
        )
    analysis_noise_models: dict[str, AnalysisNoiseModel] = {}
    analysis_noise_metadata = metadata.get("analysis_noise_model_metadata_by_microscope", {})
    if isinstance(analysis_noise_metadata, Mapping):
        for microscope, model_meta in analysis_noise_metadata.items():
            label = str(microscope)
            if label not in analysis_noise_diagonal:
                continue
            payload = dict(model_meta or {})
            payload["diagonal_variance"] = analysis_noise_diagonal[label]
            if label in analysis_noise_couplings:
                payload["row_correlated_couplings"] = analysis_noise_couplings[label]
            analysis_noise_models[label] = analysis_noise_model_from_likelihood(
                payload,
                context=f"loaded packet analysis_noise_model_by_microscope[{label!r}]",
            )
    packet = {
        "metadata": metadata,
        "images_by_microscope": images,
        "raw_images_by_microscope": raw_images,
        "rendered_signal_frame_by_microscope": rendered_signal_frames,
        "reference_frame_by_microscope": reference_frames,
        "noise_variance_by_microscope": noise_variance_maps,
        "analysis_noise_model_by_microscope": analysis_noise_models,
        "fisher_by_microscope": fishers,
        "crlb_by_microscope": dict(metadata.get("crlb_by_microscope", {}) or {}),
        "masks": masks,
    }
    validate_matched_microscope_packet(packet)
    return packet


def validate_matched_microscope_packet(packet: Mapping[str, Any]) -> None:
    """Validate a loaded or in-memory matched microscope packet."""

    metadata = dict(packet.get("metadata", {}) or {})
    packet_extra = dict(metadata.get("metadata", {}) or {})
    build_matched_microscope_packet(
        latent_state=dict(metadata.get("latent_state", {}) or {}),
        images_by_microscope=dict(packet.get("images_by_microscope", {}) or {}),
        modality_by_microscope=dict(metadata.get("modality_by_microscope", {}) or {}),
        raw_images_by_microscope=dict(packet.get("raw_images_by_microscope", {}) or {}),
        rendered_signal_frame_by_microscope=dict(packet.get("rendered_signal_frame_by_microscope", {}) or {}),
        reference_frame_by_microscope=dict(packet.get("reference_frame_by_microscope", {}) or {}),
        noise_variance_by_microscope=dict(packet.get("noise_variance_by_microscope", {}) or {}),
        analysis_noise_model_by_microscope=dict(packet.get("analysis_noise_model_by_microscope", {}) or {}),
        masks=dict(packet.get("masks", {}) or {}),
        fisher_by_microscope=dict(packet.get("fisher_by_microscope", {}) or {}),
        crlb_by_microscope=dict(metadata.get("crlb_by_microscope", {}) or {}),
        metadata=packet_extra,
        require_information_fields=metadata.get("packet_kind") == MATCHED_MICROSCOPE_PACKET_KIND,
    )


__all__ = [
    "MATCHED_MICROSCOPE_IMAGE_PACKET_KIND",
    "MATCHED_MICROSCOPE_IMAGE_PACKET_SCHEMA_VERSION",
    "MATCHED_MICROSCOPE_PACKET_KIND",
    "MATCHED_MICROSCOPE_PACKET_SCHEMA_VERSION",
    "build_matched_microscope_packet",
    "load_matched_microscope_packet",
    "save_matched_microscope_packet",
    "validate_matched_microscope_packet",
]
