"""Electron parameter-schema fragment."""

from __future__ import annotations

from ._spec import ParamSpec


ELECTRON_SCHEMA: dict[str, ParamSpec] = {
"tem_model": ParamSpec(
    key="tem_model",
    type="enum",
    default="syniscopy_multislice",
    choices=[
        "weak_phase_ctf",
        "ctf_proxy",
        "multislice_lite",
        "syniscopy_multislice",
    ],
    ui_label="TEM model",
    group="Advanced modality",
    description=(
        "Syniscopy-native high-fidelity multislice by default; legacy weak-phase CTF "
        "(alias 'ctf_proxy') and projected-phase multislice-lite are available for "
        "reduced-fidelity benchmarking."
    ),
),
"tem_backend": ParamSpec(
    key="tem_backend",
    type="enum",
    default="syniscopy_multislice",
    choices=[
        "ctf_proxy",
        "multislice_lite",
        "syniscopy_multislice",
    ],
    ui_label="TEM backend",
    group="Advanced modality",
    description="Selects Syniscopy high-fidelity multislice by default; legacy weak-phase CTF and Syniscopy native multislice-lite proxy remain available.",
),
"tem_objective_aperture_mrad": ParamSpec(
    key="tem_objective_aperture_mrad",
    type="float",
    default=None,
    min=1e-4,
    max=1e3,
    ui_label="TEM objective aperture (mrad)",
    group="Advanced modality",
    description="Optional objective-aperture cut-off in mrad for Syniscopy multislice objective transfer.",
),
"tem_slice_thickness_nm": ParamSpec(
    key="tem_slice_thickness_nm",
    type="float",
    default=5.0,
    min=1e-6,
    max=1e9,
    ui_label="TEM z-slice thickness (nm)",
    group="Advanced modality",
    description="Slice thickness for syniscopy_multislice. Required when TEM high-fidelity backend is selected.",
),
"tem_multislice_slices": ParamSpec(
    key="tem_multislice_slices",
    type="int",
    default=8,
    min=1,
    max=2048,
    ui_label="TEM multislice stack slices",
    group="Advanced modality",
    description="Number of axial slices used by Syniscopy multislice electron transfer.",
),
"tem_acceleration_kV": ParamSpec(
    key="tem_acceleration_kV",
    type="float",
    default=300.0,
    min=1.0,
    max=5000.0,
    ui_label="TEM accelerating voltage (kV)",
    group="Advanced modality",
    description="Accelerating voltage for relativistic electron wavelength and interaction parameter.",
),
"tem_Cs_mm": ParamSpec(
    key="tem_Cs_mm",
    type="float",
    default=0.5,
    min=0.0,
    max=1000.0,
    ui_label="TEM spherical aberration C_s (mm)",
    group="Advanced modality",
    description="Spherical aberration coefficient used by high-fidelity TEM transfer functions.",
),
"tem_partial_coherence_alpha_mrad": ParamSpec(
    key="tem_partial_coherence_alpha_mrad",
    type="float",
    default=0.1,
    min=0.0,
    max=1000.0,
    ui_label="TEM partial-coherence half-angle (mrad)",
    group="Advanced modality",
    description="Coherent-illumination angular width used in envelope damping.",
),
"tem_defocus_nm": ParamSpec(
    key="tem_defocus_nm",
    type="float",
    default=None,
    min=-1e9,
    max=1e9,
    ui_label="TEM defocus (nm)",
    group="Advanced modality",
    description="Nominal defocus offset in nanometers; defaults to Scherzer when unset.",
),
"tem_pixel_size_pm": ParamSpec(
    key="tem_pixel_size_pm",
    type="float",
    default=None,
    min=1e-6,
    max=1e9,
    ui_label="TEM pixel size compatibility check (pm)",
    group="Advanced modality",
    description="Compatibility-only check against rendered pixel pitch when provided.",
),
"tem_dose_per_pixel": ParamSpec(
    key="tem_dose_per_pixel",
    type="float",
    default=100.0,
    min=0.0,
    max=1e12,
    ui_label="TEM dose per pixel",
    group="Advanced modality",
    description="Average electron count budget per pixel before poissonization/scaling.",
),
"tem_potential_source": ParamSpec(
    key="tem_potential_source",
    type="enum",
    default="material_projected_inner_potential",
    choices=[
        "material_projected_inner_potential",
        "sample_environment_projected_potential",
        "material_plus_sample_environment",
    ],
    ui_label="TEM potential source",
    group="Advanced modality",
    description=(
        "Selects whether projected TEM phase comes from material only, "
        "sample-environment only, or composite material plus sample-environment."
    ),
),
"tem_reference_status": ParamSpec(
    key="tem_reference_status",
    type="enum",
    default="physics_based_unvalidated",
    choices=["physics_based_unvalidated", "reference_validated"],
    ui_label="TEM reference status",
    group="Advanced modality",
    description="Reference metadata state associated with Syniscopy multislice TEM output.",
),
"tem_reference_validation_hash": ParamSpec(
    key="tem_reference_validation_hash",
    type="string",
    default=None,
    ui_label="TEM reference validation hash",
    group="Advanced modality",
    description="SHA-256 digest required when tem_reference_status is reference_validated.",
),
"tem_filter_guard_pixels": ParamSpec(
    key="tem_filter_guard_pixels",
    type="int",
    default=64,
    min=0,
    max=4096,
    ui_label="TEM filter guard pixels",
    group="Advanced modality",
    description="Spatial guard region in pixels for TEM transfer filtering.",
),
"tem_sample_environment_potential_scale": ParamSpec(
    key="tem_sample_environment_potential_scale",
    type="float",
    default=1.0e-4,
    min=0.0,
    max=10.0,
    ui_label="TEM sample-environment potential scale",
    group="Advanced modality",
    description="Scaling for sample-environment projected-potential contribution.",
),
"tem_projected_potential_scale": ParamSpec(
    key="tem_projected_potential_scale",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="TEM projected-potential scale",
    group="Advanced modality",
    description="Relative gain applied to projected inner-potential-derived phase map.",
),
"tem_phase_shift_per_volt_nm": ParamSpec(
    key="tem_phase_shift_per_volt_nm",
    type="float",
    default=None,
    min=0.0,
    max=1e12,
    ui_label="TEM phase shift per volt-nm",
    group="Advanced modality",
    description="Override the electron interaction parameter in weak-phase projection models.",
),
"sem_model": ParamSpec(
    key="sem_model",
    type="enum",
    default="gaussian_probe_proxy",
    choices=[
        "gaussian_probe_proxy",
        "gaussian_probe_secondary_yield",
        "interaction_volume_proxy",
    ],
    ui_label="SEM model",
    group="Advanced modality",
    description=(
        "Gaussian-probe secondary-yield proxy. ``gaussian_probe_proxy`` and "
        "``gaussian_probe_secondary_yield`` are aliases; use "
        "``interaction_volume_proxy`` for the interaction-volume proxy."
    ),
),
"sem_backend": ParamSpec(
    key="sem_backend",
    type="enum",
    default="monte_carlo_transport",
    choices=[
        "gaussian_probe_proxy",
        "interaction_volume_proxy",
        "monte_carlo_transport",
        "syniscopy_transport_lite",
        "reference_kernel_table",
    ],
    ui_label="SEM backend",
    group="Advanced modality",
    description="Selects SEM forward model fidelity: Monte Carlo interaction-volume default, transport-lite/proxy variants, or reference-kernel table variants.",
),
"sem_source_representation": ParamSpec(
    key="sem_source_representation",
    type="enum",
    default="volume",
    choices=[
        "projected",
        "volume",
    ],
    ui_label="SEM source representation",
    group="Advanced modality",
    description="Selects whether SEM particle material is accumulated as a projected 2D source map or as a sliced z-y-x source volume for volume-capable backends.",
),
"sem_volume_slices": ParamSpec(
    key="sem_volume_slices",
    type="int",
    default=8,
    min=1,
    max=2048,
    ui_label="SEM source volume slices",
    group="Advanced modality",
    description="Number of axial source slices used when SEM source representation is volume.",
),
"sem_volume_slice_thickness_nm": ParamSpec(
    key="sem_volume_slice_thickness_nm",
    type="float",
    default=None,
    min=1e-9,
    max=1e7,
    ui_label="SEM source slice thickness (nm)",
    group="Advanced modality",
    description="Optional axial slice thickness for SEM source volumes; defaults from the interaction-volume depth divided by sem_volume_slices.",
),
"sem_source_z_origin": ParamSpec(
    key="sem_source_z_origin",
    type="enum",
    default="entry_surface_depth",
    choices=[
        "entry_surface_depth",
        "focus_plane_relative",
    ],
    ui_label="SEM source z origin",
    group="Advanced modality",
    description="Axial convention for SEM source volumes: local entry-surface depth or focus-plane-relative scene z.",
),
"sem_source_z_offset_nm": ParamSpec(
    key="sem_source_z_offset_nm",
    type="float",
    default=0.0,
    min=-1e9,
    max=1e9,
    ui_label="SEM source z offset (nm)",
    group="Advanced modality",
    description="Axial offset applied when placing SEM source-volume slices.",
),
"sem_beam_current_nA": ParamSpec(
    key="sem_beam_current_nA",
    type="float",
    default=0.0,
    min=0.0,
    max=1.0e6,
    ui_label="SEM beam current (nA)",
    group="Advanced modality",
    description="Beam current used to derive electron dose per pixel (nA).",
),
"sem_dwell_time_us": ParamSpec(
    key="sem_dwell_time_us",
    type="float",
    default=0.0,
    min=0.0,
    max=1.0e6,
    ui_label="SEM dwell time (µs)",
    group="Advanced modality",
    description="Pixel dwell time in microseconds.",
),
"sem_detector_takeoff_angle_deg": ParamSpec(
    key="sem_detector_takeoff_angle_deg",
    type="float",
    default=45.0,
    min=0.0,
    max=180.0,
    ui_label="SEM takeoff angle (deg)",
    group="Advanced modality",
    description="Detector takeoff angle in degrees for geometry scaling.",
),
"sem_detector_acceptance": ParamSpec(
    key="sem_detector_acceptance",
    type="float",
    default=1.0,
    min=0.0,
    max=1.0,
    ui_label="SEM detector acceptance",
    group="Advanced modality",
    description="Scalar detector acceptance factor in [0, 1].",
),
"sem_escape_depth_nm": ParamSpec(
    key="sem_escape_depth_nm",
    type="float",
    default=20.0,
    min=0.0,
    max=1000.0,
    ui_label="SEM escape depth (nm)",
    group="Advanced modality",
    description="Escape-depth proxy used by transport backend blur and source scaling.",
),
"sem_backscatter_fraction": ParamSpec(
    key="sem_backscatter_fraction",
    type="float",
    default=0.05,
    min=0.0,
    max=1.0,
    ui_label="SEM backscatter fraction",
    group="Advanced modality",
    description="Additive secondary contribution from the backscatter fraction term.",
),
"sem_transport_material_scale": ParamSpec(
    key="sem_transport_material_scale",
    type="float",
    default=1.0,
    min=0.0,
    max=10.0,
    ui_label="SEM material scale",
    group="Advanced modality",
    description="Transport material-response gain multiplier.",
),
"sem_transport_source_exponent": ParamSpec(
    key="sem_transport_source_exponent",
    type="float",
    default=1.0,
    min=0.01,
    max=5.0,
    ui_label="SEM source exponent",
    group="Advanced modality",
    description="Exponent applied to source map in transport backend.",
),
"sem_transport_topography_exponent": ParamSpec(
    key="sem_transport_topography_exponent",
    type="float",
    default=1.0,
    min=0.01,
    max=5.0,
    ui_label="SEM topography exponent",
    group="Advanced modality",
    description="Exponent applied to directed topography term in transport backend.",
),
"sem_monte_carlo_trajectories": ParamSpec(
    key="sem_monte_carlo_trajectories",
    type="int",
    default=4096,
    min=1,
    max=1000000,
    ui_label="SEM MC trajectories",
    group="Advanced modality",
    description="Number of electron random-walk trajectories used to precompute the SEM Monte Carlo interaction kernel.",
),
"sem_monte_carlo_steps": ParamSpec(
    key="sem_monte_carlo_steps",
    type="int",
    default=64,
    min=1,
    max=10000,
    ui_label="SEM MC steps",
    group="Advanced modality",
    description="Maximum random-walk steps per electron trajectory in the SEM Monte Carlo interaction kernel.",
),
"sem_monte_carlo_seed": ParamSpec(
    key="sem_monte_carlo_seed",
    type="int",
    default=None,
    min=0,
    max=2147483647,
    ui_label="SEM MC seed",
    group="Advanced modality",
    description="Optional deterministic seed for the SEM Monte Carlo interaction kernel.",
),
"sem_monte_carlo_step_nm": ParamSpec(
    key="sem_monte_carlo_step_nm",
    type="float",
    default=None,
    min=1e-9,
    max=1e6,
    ui_label="SEM MC step (nm)",
    group="Advanced modality",
    description="Optional random-walk step length in nanometers; defaults from range/step count.",
),
"sem_monte_carlo_range_nm": ParamSpec(
    key="sem_monte_carlo_range_nm",
    type="float",
    default=None,
    min=1e-9,
    max=1e7,
    ui_label="SEM MC range (nm)",
    group="Advanced modality",
    description="Optional interaction range before beam-energy scaling; defaults from sem_interaction_volume_nm.",
),
"sem_monte_carlo_scatter_std_deg": ParamSpec(
    key="sem_monte_carlo_scatter_std_deg",
    type="float",
    default=8.0,
    min=0.0,
    max=180.0,
    ui_label="SEM MC scatter std",
    group="Advanced modality",
    description="Per-step angular scatter standard deviation in degrees at 5 kV, scaled by beam energy.",
),
"sem_monte_carlo_kernel_size_px": ParamSpec(
    key="sem_monte_carlo_kernel_size_px",
    type="int",
    default=None,
    min=1,
    max=8192,
    ui_label="SEM MC kernel size",
    group="Advanced modality",
    description="Optional odd interaction-kernel size in canvas pixels; even values are rounded up internally.",
),
"sem_reference_material": ParamSpec(
    key="sem_reference_material",
    type="string",
    default="default",
    ui_label="SEM reference material",
    group="Advanced modality",
    description="Material selector for kernel-table row matching.",
),
"sem_reference_geometry": ParamSpec(
    key="sem_reference_geometry",
    type="string",
    default="normal",
    ui_label="SEM reference geometry",
    group="Advanced modality",
    description="Geometry selector for kernel-table row matching.",
),
"sem_reference_source_depth_nm": ParamSpec(
    key="sem_reference_source_depth_nm",
    type="float",
    default=0.0,
    min=0.0,
    max=1000.0,
    ui_label="SEM reference source depth (nm)",
    group="Advanced modality",
    description="Source depth in nanometers for kernel-table interpolation.",
),
"sem_reference_incident_angle_deg": ParamSpec(
    key="sem_reference_incident_angle_deg",
    type="float",
    default=0.0,
    min=0.0,
    max=180.0,
    ui_label="SEM reference incident angle (deg)",
    group="Advanced modality",
    description="Incident-angle query for reference-kernel interpolation.",
),
"sem_detector_direction_xy": ParamSpec(
    key="sem_detector_direction_xy",
    type="json",
    default=[1.0, 0.0],
    ui_label="SEM detector direction",
    group="Advanced modality",
    description="2D SEM detector direction unit vector in the detector plane.",
),
"sem_acceleration_kV": ParamSpec(
    key="sem_acceleration_kV",
    type="float",
    default=5.0,
    min=0.1,
    max=50000.0,
    ui_label="SEM accelerating voltage (kV)",
    group="Advanced modality",
    description="Beam energy used by Syniscopy SEM transport/reference backends.",
),
"sem_interaction_volume_nm": ParamSpec(
    key="sem_interaction_volume_nm",
    type="float",
    default=30.0,
    min=0.0,
    max=10000.0,
    ui_label="SEM interaction volume depth (nm)",
    group="Advanced modality",
    description="Depth for interaction-volume proxy gain shaping.",
),
"sem_filter_guard_pixels": ParamSpec(
    key="sem_filter_guard_pixels",
    type="int",
    default=None,
    min=0,
    max=4096,
    ui_label="SEM filter guard pixels",
    group="Advanced modality",
    description="Spatial guard region in pixels for SEM transfer filtering.",
),
"sem_probe_sigma_nm": ParamSpec(
    key="sem_probe_sigma_nm",
    type="float",
    default=None,
    min=0.0,
    max=1e6,
    ui_label="SEM probe sigma (nm)",
    group="Advanced modality",
    description="Beam probe standard deviation in nanometers; computed from pixels when unset.",
),
"sem_probe_sigma_pixels": ParamSpec(
    key="sem_probe_sigma_pixels",
    type="float",
    default=1.0,
    min=0.0,
    max=1e4,
    ui_label="SEM probe sigma (pixels)",
    group="Advanced modality",
    description="Legacy SEM probe sigma parameter in render pixels.",
),
"sem_edge_contrast_gain": ParamSpec(
    key="sem_edge_contrast_gain",
    type="float",
    default=10.0,
    min=0.0,
    max=1e6,
    ui_label="SEM edge contrast gain",
    group="Advanced modality",
    description="Gain for image-gradient driven secondary-electron edge term.",
),
"sem_bulk_contrast_gain": ParamSpec(
    key="sem_bulk_contrast_gain",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="SEM bulk contrast gain",
    group="Advanced modality",
    description="Gain applied to blur-projected bulk secondary-electron source.",
),
"sem_topography_contrast_gain": ParamSpec(
    key="sem_topography_contrast_gain",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="SEM topography contrast gain",
    group="Advanced modality",
    description="Gain for topography-normal response term in transport model.",
),
"sem_sample_environment_edge_gain": ParamSpec(
    key="sem_sample_environment_edge_gain",
    type="float",
    default=10.0,
    min=0.0,
    max=1e6,
    ui_label="SEM sample-environment edge gain",
    group="Advanced modality",
    description="Gain for sample-environment boundary-contrast term.",
),
"sem_baseline_yield": ParamSpec(
    key="sem_baseline_yield",
    type="float",
    default=0.05,
    min=0.0,
    max=1e6,
    ui_label="SEM baseline yield",
    group="Advanced modality",
    description="Constant background secondary-electron yield floor.",
),
"sem_electrons_per_pixel": ParamSpec(
    key="sem_electrons_per_pixel",
    type="float",
    default=1000.0,
    min=0.0,
    max=1e15,
    ui_label="SEM fallback electrons per pixel",
    group="Advanced modality",
    description="Fallback electron budget when beam current and dwell-time are not both supplied.",
),
"sem_reference_kernel_path": ParamSpec(
    key="sem_reference_kernel_path",
    type="string",
    default=None,
    ui_label="SEM reference kernel path",
    group="Advanced modality",
    description="Path to reference-kernel table JSON for interpolation-based SEM transport.",
),
"sem_reference_kernel_sha256": ParamSpec(
    key="sem_reference_kernel_sha256",
    type="string",
    default=None,
    ui_label="SEM reference kernel SHA-256",
    group="Advanced modality",
    description="Checksum used to validate reference-kernel table provenance.",
),
}

__all__ = ["ELECTRON_SCHEMA"]
