"""Noise parameter-schema fragment."""

from __future__ import annotations

from ._spec import ParamSpec


NOISE_SCHEMA: dict[str, ParamSpec] = {
"detector_spectral_response_model": ParamSpec(
    key="detector_spectral_response_model",
    type="enum",
    default="rgb_heuristic",
    choices=["rgb_heuristic", "flat", "table"],
    ui_label="Detector spectral response",
    group="Workflow",
    description="Detector response model used for generated broadband channels.",
),
"background_subtraction_method": ParamSpec(
    key="background_subtraction_method",
    type="string",
    default="video_median",
    ui_label="Background subtraction method",
    group="Imaging",
    description="Background subtraction strategy for frame normalization.",
),
"shot_noise_enabled": ParamSpec(
    key="shot_noise_enabled",
    type="bool",
    default=True,
    ui_label="Shot noise",
    group="Noise",
    description="Enable Poisson photon/electron shot noise.",
),
"drift_velocity_nm_per_s": ParamSpec(
    key="drift_velocity_nm_per_s",
    type="json",
    default=[0.0, 0.0, 0.0],
    ui_label="Drift velocity (nm/s)",
    group="Dynamics",
    description="Rigid-frame translation rate for all particles, one value per axis in nm/s.",
),
"motion_blur_enabled": ParamSpec(
    key="motion_blur_enabled",
    type="bool",
    default=True,
    ui_label="Motion blur enabled",
    group="Dynamics",
    description="Enable per-frame motion blur during rendering.",
),
"motion_blur_subsamples": ParamSpec(
    key="motion_blur_subsamples",
    type="int",
    default=4,
    min=1,
    max=256,
    ui_label="Motion blur subsamples",
    group="Dynamics",
    description="Temporal supersampling count used when motion blur is enabled.",
),
"gaussian_noise_enabled": ParamSpec(
    key="gaussian_noise_enabled",
    type="bool",
    default=True,
    ui_label="Read / Gaussian noise",
    group="Noise",
    description="Enable Gaussian read noise (controlled by read_noise_counts).",
),
"adc_quantization": ParamSpec(
    key="adc_quantization",
    type="bool",
    default=False,
    ui_label="ADC quantization",
    group="Noise",
    description="Enable quantization after final count-space accumulation.",
),
"adc_quantization_counts": ParamSpec(
    key="adc_quantization_counts",
    type="float",
    default=1.0,
    min=0.1,
    max=1e6,
    ui_label="ADC quantization step",
    group="Noise",
    description="Quantization step size in count units when ADC quantization is enabled.",
),
"background_offset_counts": ParamSpec(
    key="background_offset_counts",
    type="float",
    default=0.0,
    min=0.0,
    max=1e12,
    ui_label="Background offset (counts)",
    group="Noise",
    description="Constant non-physical background offset added before Poisson noise.",
),
"nonlinearity_calibration": ParamSpec(
    key="nonlinearity_calibration",
    type="string",
    default=None,
    ui_label="ADC nonlinearity calibration",
    group="Noise",
    description="Optional nonlinearity calibration map or profile for count-domain response.",
),
"read_noise_e": ParamSpec(
    key="read_noise_e",
    type="float",
    default=None,
    min=0.0,
    max=1e12,
    ui_label="Read noise (e-)",
    group="Noise",
    description="Read noise specified in electrons; converted to counts when provided.",
),
"camera_gain_e_per_count": ParamSpec(
    key="camera_gain_e_per_count",
    type="float",
    default=1.0,
    min=0.001,
    max=10000.0,
    ui_label="Camera gain (e⁻/count)",
    group="Noise",
    description=(
        "Detected photoelectrons per output camera count/ADU. "
        "Controls shot-noise magnitude: σ_shot = sqrt(counts / gain). "
        "Calibrate from the real video with "
        "camera_noise.calibrate_camera_gain_e_per_count_from_video()."
    ),
),
"detector_qe": ParamSpec(
    key="detector_qe", type="float", default=1.0, min=0.0, max=1.0,
    ui_label="Detector QE", group="Noise",
    description="Generic detector quantum efficiency; neutral at 1.0 and active when detector_input_is_incident_quanta is true.",
),
"detector_input_is_incident_quanta": ParamSpec(
    key="detector_input_is_incident_quanta", type="bool", default=False,
    ui_label="Input is incident quanta", group="Noise",
    description="Apply detector_qe before detection noise when rendered values are incident quanta.",
),
"emccd_enabled": ParamSpec(
    key="emccd_enabled", type="bool", default=False, ui_label="EMCCD mode", group="Noise",
    description="Enable EMCCD excess-noise variance/sampling.",
),
"emccd_excess_noise_factor": ParamSpec(
    key="emccd_excess_noise_factor", type="float", default=1.0, min=1.0, max=4.0,
    ui_label="EMCCD excess-noise factor", group="Noise",
    description="Multiplicative shot-variance factor that must not change mean signal.",
),
"emccd_gain": ParamSpec(
    key="emccd_gain",
    type="float",
    default=1.0,
    min=0.1,
    max=1024.0,
    ui_label="EMCCD gain",
    group="Noise",
    description="EMCCD electronic gain applied as input-referred read-noise reduction when EMCCD mode is enabled.",
),
"dark_current_e_per_pixel_per_s": ParamSpec(
    key="dark_current_e_per_pixel_per_s",
    type="float",
    default=0.0,
    min=0.0,
    ui_label="Dark current (e-/pix/s)",
    group="Noise",
    description="Detector dark-current contribution in electrons per pixel per second.",
),
"exposure_time_s": ParamSpec(
    key="exposure_time_s",
    type="float",
    default=1.0,
    min=0.0,
    ui_label="Exposure time (s)",
    group="Noise",
    description="Exposure time used when converting dark current (e-) to count offsets.",
),
"read_noise_counts": ParamSpec(
    key="read_noise_counts",
    type="float",
    default=1.0,
    min=0.0,
    max=10000.0,
    ui_label="Read noise (counts RMS)",
    group="Noise",
    description=(
        "RMS Gaussian read noise in camera counts. "
        "Convert from electrons: read_noise_counts = σ_e / camera_gain_e_per_count."
    ),
),
"saturation_level": ParamSpec(
    key="saturation_level",
    type="float",
    default=None,
    ui_label="Saturation level (counts)",
    group="Noise",
    description="Output-level saturation clamp in camera counts; None disables count-domain clipping.",
),
"saturation_e": ParamSpec(
    key="saturation_e",
    type="float",
    default=None,
    ui_label="Saturation level (e-)",
    group="Noise",
    description="Absolute saturation clamp in electrons before conversion to counts; None disables.",
),
"dark_offset_counts": ParamSpec(
    key="dark_offset_counts",
    type="float",
    default=0.0,
    ui_label="Dark/frame offset (counts)",
    group="Noise",
    description="Constant additive offset in camera counts added before fixed-pattern and Poisson steps.",
),
"fixed_pattern_gain_std": ParamSpec(
    key="fixed_pattern_gain_std",
    type="float",
    default=0.0,
    min=0.0,
    ui_label="Fixed-pattern gain std",
    group="Noise",
    description="Std dev of random fixed-pattern gain map, zero by default.",
),
"fixed_pattern_offset_counts": ParamSpec(
    key="fixed_pattern_offset_counts",
    type="float",
    default=0.0,
    ui_label="Fixed-pattern offset std (counts)",
    group="Noise",
    description="Std dev of random fixed-pattern additive offset map, zero by default.",
),
"scan_line_noise_counts": ParamSpec(
    key="scan_line_noise_counts",
    type="float",
    default=0.0,
    min=0.0,
    ui_label="Scan-line noise (counts RMS)",
    group="Noise",
    description="Additive row-correlated noise in counts, used for rolling-shutter / ADC coupling.",
),
"hot_pixel_fraction": ParamSpec(
    key="hot_pixel_fraction",
    type="float",
    default=0.0,
    min=0.0,
    max=1.0,
    ui_label="Hot-pixel fraction",
    group="Noise",
    description="Fraction of pixels flagged as hot pixels.",
),
"clip_output_to_nonnegative": ParamSpec(
    key="clip_output_to_nonnegative",
    type="bool",
    default=True,
    ui_label="Clip output to nonnegative",
    group="Noise",
    description="Clamp final noisy counts to a nonnegative range.",
),
"noise_parameterization": ParamSpec(
    key="noise_parameterization",
    type="enum",
    default="camera_counts",
    choices=["camera_counts"],
    ui_label="Noise parameterization",
    group="Noise",
    description="Top-level noise domain; only 'camera_counts' is currently implemented.",
),
"detector_noise_input_domain": ParamSpec(
    key="detector_noise_input_domain",
    type="enum",
    default=None,
    choices=["camera_counts", "electron_count"],
    ui_label="Detector-noise input domain",
    group="Noise",
    description=(
        "Optional detector-noise input-domain override. None derives from the "
        "canonical modality."
    ),
),
"read_noise_map_mode": ParamSpec(
    key="read_noise_map_mode",
    type="enum",
    default="replace",
    choices=["replace", "add"],
    ui_label="Read-noise map mode",
    group="Noise",
    description="How per-pixel read-noise maps combine with scalar read noise.",
),
"modality_noise": ParamSpec(
    key="modality_noise",
    type="json",
    default={},
    ui_label="Modalities noise overrides",
    group="Noise",
    description="Per-modality nested overrides for noise parameters.",
),
"noise_model": ParamSpec(
    key="noise_model",
    type="json",
    default={},
    ui_label="Noise model overrides",
    group="Noise",
    description="Global grouped overrides for noise-domain parameters.",
),
"fixed_pattern_gain_map": ParamSpec(
    key="fixed_pattern_gain_map",
    type="string",
    default=None,
    ui_label="Fixed-pattern gain map",
    group="Noise",
    description="Path or inline scalar for deterministic fixed-pattern gain map.",
),
"hot_pixel_value_counts": ParamSpec(
    key="hot_pixel_value_counts",
    type="float",
    default=None,
    min=0.0,
    ui_label="Hot-pixel value (counts)",
    group="Noise",
    description="Saturation value assigned to hot pixels. None uses frame maximum.",
),
"scmos_gain_map": ParamSpec(
    key="scmos_gain_map",
    type="string",
    default=None,
    ui_label="sCMOS gain map",
    group="Noise",
    description="Optional per-pixel multiplicative gain map for sCMOS-like nonuniform gain.",
),
"fixed_pattern_offset_map": ParamSpec(
    key="fixed_pattern_offset_map",
    type="string",
    default=None,
    ui_label="Fixed-pattern offset map",
    group="Noise",
    description="Path or inline scalar for deterministic DSNU/offset map.",
),
"hot_pixel_mask": ParamSpec(
    key="hot_pixel_mask",
    type="string",
    default=None,
    ui_label="Hot-pixel mask",
    group="Noise",
    description="Path or inline scalar/array mask for deterministic hot pixels.",
),
"scmos_variance_map": ParamSpec(
    key="scmos_variance_map",
    type="string",
    default=None,
    ui_label="sCMOS variance map",
    group="Noise",
    description="Path or inline scalar/array of per-pixel read-noise variance.",
),
"scmos_read_noise_map": ParamSpec(
    key="scmos_read_noise_map",
    type="string",
    default=None,
    ui_label="sCMOS read-noise map",
    group="Noise",
    description="Path or inline scalar/array of per-pixel read-noise standard deviation.",
),
"flat_field_map": ParamSpec(
    key="flat_field_map",
    type="string",
    default=None,
    ui_label="Flat-field map",
    group="Noise",
    description="Path or scalar multiplicative gain map applied to detector output.",
),
"dark_frame_map": ParamSpec(
    key="dark_frame_map",
    type="string",
    default=None,
    ui_label="Dark-frame map",
    group="Noise",
    description="Path or scalar dark-frame offset map added in detector counts.",
),
}

__all__ = ["NOISE_SCHEMA"]
