"""Optics parameter-schema fragment."""

from __future__ import annotations

from ._spec import ParamSpec
from modality_registry import SUPPORTED_MODALITIES


OPTICS_SCHEMA: dict[str, ParamSpec] = {
"imaging_model": ParamSpec(
    key="imaging_model",
    type="enum",
    default="bright_field",
    choices=list(SUPPORTED_MODALITIES),
    ui_label="Imaging modality",
    group="Imaging",
    description="Canonical contrast model used for rendering.",
),
"wavelength_nm": ParamSpec(
    key="wavelength_nm",
    type="float",
    default=635.0,
    min=400.0,
    max=800.0,
    ui_label="Wavelength (nm)",
    group="Optics",
    description="Illumination wavelength in vacuum (nm).",
),
"probe_wavelength_nm": ParamSpec(
    key="probe_wavelength_nm",
    type="float",
    default=None,
    min=1.0,
    max=1e5,
    ui_label="Probe wavelength (nm)",
    group="Optics",
    description="Optional modality-specific probe wavelength; overrides the global illumination wavelength.",
),
"numerical_aperture": ParamSpec(
    key="numerical_aperture",
    type="float",
    default=1.2,
    min=0.8,
    max=1.49,
    ui_label="Numerical aperture",
    group="Optics",
    description="Objective numerical aperture.",
),
"optical_field_backend": ParamSpec(
    key="optical_field_backend",
    type="enum",
    default="vectorial_debye",
    choices=["scalar_paraxial", "vectorial_debye"],
    ui_label="Optical field backend",
    group="Optics",
    description="Scalar paraxial PSF or vectorial Debye/Richards-Wolf PSF backend.",
),
"polarization_model": ParamSpec(
    key="polarization_model",
    type="enum",
    default="linear_x",
    choices=["scalar", "linear_x", "linear_y", "unpolarized"],
    ui_label="Polarization model",
    group="Optics",
    description=(
        "Incident polarization model used by the optical field backend. "
        "Unpolarized is an incoherent average and is not valid as a single "
        "coherent full-vector reference field."
    ),
),
"vectorial_detection_mode": ParamSpec(
    key="vectorial_detection_mode",
    type="enum",
    default="full_vector",
    choices=["incoherent_sum", "analyzer_x", "analyzer_y", "unpolarized", "full_vector"],
    ui_label="Vectorial detection",
    group="Optics",
    description=(
        "Vectorial Debye field handling. full_vector transports Ex/Ey/Ez "
        "to vector-aware coherent models; analyzer_x/analyzer_y are coherent "
        "scalar projections; incoherent_sum and unpolarized are intensity "
        "proxies and are rejected for coherent-reference modalities."
    ),
),
"vectorial_polarization_rotation_deg": ParamSpec(
    key="vectorial_polarization_rotation_deg",
    type="float",
    default=0.0,
    ui_label="Vectorial polarization rotation (deg)",
    group="Optics",
    min=-360.0,
    max=360.0,
    description="Linear polarization basis rotation around the optical axis.",
),
"vectorial_pupil_samples": ParamSpec(
    key="vectorial_pupil_samples",
    type="int",
    default=None,
    min=8,
    max=2048,
    ui_label="Vectorial pupil samples",
    group="Optics",
    description="Optional pupil-grid size for vectorial Debye calculations.",
),
"pupil_samples": ParamSpec(
    key="pupil_samples",
    type="int",
    default=512,
    min=8,
    max=8192,
    ui_label="Pupil samples",
    group="Optics",
    description="Global pupil sampling resolution for optical field calculations.",
),
"psf_oversampling_factor": ParamSpec(
    key="psf_oversampling_factor",
    type="int",
    default=2,
    min=1,
    max=64,
    ui_label="PSF oversampling factor",
    group="Optics",
    description="Oversampling factor between detector pixels and optical field grid.",
),
"z_stack_range_nm": ParamSpec(
    key="z_stack_range_nm",
    type="float",
    default=30500.0,
    min=1e-6,
    max=1e9,
    ui_label="Z stack range (nm)",
    group="Optics",
    description="Total axial extent in nanometers covered by sampled PSF stacks.",
),
"z_stack_step_nm": ParamSpec(
    key="z_stack_step_nm",
    type="float",
    default=50.0,
    min=1e-6,
    max=1e9,
    ui_label="Z stack step (nm)",
    group="Optics",
    description="Axial spacing between PSF stack slices in nanometers.",
),
"max_psf_z_slices": ParamSpec(
    key="max_psf_z_slices",
    type="int",
    default=4096,
    min=1,
    max=1000000,
    ui_label="Max PSF z slices",
    group="Optics",
    description="Safety cap for automatically generated optical stack size.",
),
"shared_psf_z_grid_enabled": ParamSpec(
    key="shared_psf_z_grid_enabled",
    type="bool",
    default=False,
    ui_label="Share PSF z grid",
    group="Optics",
    description="Reuse one optical z-grid across compatible modality renders when enabled.",
),
"psf_intensity_fraction_threshold": ParamSpec(
    key="psf_intensity_fraction_threshold",
    type="float",
    default=1e-4,
    min=0.0,
    max=1.0,
    ui_label="PSF intensity threshold",
    group="Optics",
    description="Fractional threshold for truncating negligible PSF tails.",
),
"spherical_aberration_strength": ParamSpec(
    key="spherical_aberration_strength",
    type="float",
    default=0.25,
    min=0.0,
    max=1e6,
    ui_label="Spherical aberration strength",
    group="Optics",
    description="Aberration strength parameter used by optical transfer modeling.",
),
"apodization_factor": ParamSpec(
    key="apodization_factor",
    type="float",
    default=1.8,
    min=0.0,
    max=10.0,
    ui_label="Apodization factor",
    group="Optics",
    description="PSF/transfer apodization factor.",
),
"random_aberration_strength": ParamSpec(
    key="random_aberration_strength",
    type="float",
    default=1.5,
    min=0.0,
    max=1e6,
    ui_label="Random aberration strength",
    group="Optics",
    description="Random aberration amplitude for synthetic optical perturbations.",
),
"refractive_index_medium": ParamSpec(
    key="refractive_index_medium",
    type="float",
    default=1.33,
    min=1.0,
    max=3.0,
    ui_label="Medium refractive index",
    group="Optics",
    description="Refractive index of immersion/ambient medium around sample.",
),
"refractive_index_immersion": ParamSpec(
    key="refractive_index_immersion",
    type="float",
    default=1.518,
    min=1.0,
    max=3.0,
    ui_label="Immersion refractive index",
    group="Optics",
    description="Refractive index of immersion material at objective front end.",
),
"objective_model": ParamSpec(
    key="objective_model",
    type="string",
    default=None,
    ui_label="Objective model",
    group="Optics",
    description="Optional objective model metadata string for provenance.",
),
"objective_focal_length_mm": ParamSpec(
    key="objective_focal_length_mm",
    type="float",
    default=3.0,
    min=1.0,
    max=1000.0,
    ui_label="Objective focal length (mm)",
    group="Optics",
    description="Objective focal length in millimeters.",
),
"magnification": ParamSpec(
    key="magnification",
    type="float",
    default=60.0,
    min=1.0,
    max=500.0,
    ui_label="Objective magnification",
    group="Optics",
    description="Nominal objective magnification used for metadata.",
),
"vectorial_obliquity_apodization": ParamSpec(
    key="vectorial_obliquity_apodization",
    type="bool",
    default=True,
    ui_label="Vectorial apodization (sqrt cos θ)",
    group="Optics",
    description="Enable aplanatic sqrt(cosθ) weighting in the vectorial Debye pupil.",
),
"coverslip_aberration_model": ParamSpec(
    key="coverslip_aberration_model",
    type="enum",
    default="none",
    choices=["none", "gibson_lanni", "coverslip_mismatch"],
    ui_label="Coverslip aberration",
    group="Optics",
    description="Optional Gibson-Lanni-style coverslip mismatch pupil OPD phase.",
),
"coverslip_thickness_um": ParamSpec(
    key="coverslip_thickness_um",
    type="float",
    default=170.0,
    min=0.0,
    max=5000.0,
    ui_label="Coverslip thickness (um)",
    group="Optics",
    description="Actual coverslip thickness used by the coverslip-aberration OPD model.",
),
"coverslip_design_thickness_um": ParamSpec(
    key="coverslip_design_thickness_um",
    type="float",
    default=170.0,
    min=0.0,
    max=5000.0,
    ui_label="Design coverslip thickness (um)",
    group="Optics",
    description="Nominal design coverslip thickness for mismatch OPD subtraction.",
),
"coverslip_refractive_index": ParamSpec(
    key="coverslip_refractive_index",
    type="float",
    default=1.518,
    min=1e-9,
    max=5.0,
    ui_label="Coverslip refractive index",
    group="Optics",
    description="Actual coverslip refractive index for the OPD model.",
),
"coverslip_design_refractive_index": ParamSpec(
    key="coverslip_design_refractive_index",
    type="float",
    default=1.518,
    min=1e-9,
    max=5.0,
    ui_label="Design coverslip index",
    group="Optics",
    description="Nominal design coverslip refractive index for OPD subtraction.",
),
"coverslip_aberration_subtract_piston": ParamSpec(
    key="coverslip_aberration_subtract_piston",
    type="bool",
    default=True,
    ui_label="Subtract coverslip piston",
    group="Optics",
    description="Remove the pupil-mean coverslip OPD phase before PSF formation.",
),
"reference_field_amplitude": ParamSpec(
    key="reference_field_amplitude",
    type="int",
    default=1,
    min=0,
    max=1000000,
    ui_label="Reference field amplitude",
    group="Optics",
    description="Global complex-reference-field amplitude for interferometric models.",
),
"dpc_channel_model": ParamSpec(
    key="dpc_channel_model",
    type="enum",
    default="vectorial_debye_asymmetric_illumination",
    choices=[
        "two_axis_scalar_asymmetric_illumination",
        "scalar_asymmetric_illumination",
        "scalar",
        "vectorial_debye_asymmetric_illumination",
        "two_axis_vectorial_debye_asymmetric_illumination",
        "vectorial",
    ],
    ui_label="DPC channel model",
    group="Imaging",
    description=(
        "Scalar or vectorial DPC backend selector. "
        "Differential-phase-contrast defaults to vectorial Debye analyzer "
        "projection and falls back to scalar aliases when requested."
    ),
),
"dpc_transfer_model": ParamSpec(
    key="dpc_transfer_model",
    type="enum",
    default="pupil_half_plane_intensity",
    choices=[
        "pupil_half_plane_intensity",
        "half_pupil_intensity",
        "asymmetric_pupil_intensity",
        "phase_gradient_proxy",
        "phase_gradient",
        "legacy_phase_gradient",
    ],
    ui_label="DPC transfer model",
    group="Imaging",
    description=(
        "Differential phase-contrast transfer model. The default computes "
        "opposite half-pupil intensity images in objective-pupil coordinates; "
        "the phase-gradient option is retained for legacy comparisons."
    ),
),
"dpc_output_channel": ParamSpec(
    key="dpc_output_channel",
    type="enum",
    default="x",
    choices=["x", "y", "diagonal", "magnitude"],
    ui_label="DPC output channel",
    group="Imaging",
    description="Orientation reported by the selected DPC transfer model.",
),
"dpc_intensity_gain": ParamSpec(
    key="dpc_intensity_gain",
    type="float",
    default=1.0,
    min=0.0,
    max=1e8,
    ui_label="DPC intensity gain",
    group="Imaging",
    description="Legacy fallback gain for pupil half-plane DPC intensity differences.",
),
"dpc_intensity_gain_x": ParamSpec(
    key="dpc_intensity_gain_x",
    type="float",
    default=1.0,
    min=0.0,
    max=1e8,
    ui_label="DPC intensity gain (x)",
    group="Imaging",
    description="Scale factor for x-oriented half-pupil DPC intensity differences.",
),
"dpc_intensity_gain_y": ParamSpec(
    key="dpc_intensity_gain_y",
    type="float",
    default=1.0,
    min=0.0,
    max=1e8,
    ui_label="DPC intensity gain (y)",
    group="Imaging",
    description="Scale factor for y-oriented half-pupil DPC intensity differences.",
),
"dpc_phase_gradient_gain_x": ParamSpec(
    key="dpc_phase_gradient_gain_x",
    type="float",
    default=2500.0,
    min=0.0,
    max=1e8,
    ui_label="DPC phase-gradient gain (x)",
    group="Imaging",
    description="Scale factor for the x-gradient component in DPC.",
),
"dpc_phase_gradient_gain_y": ParamSpec(
    key="dpc_phase_gradient_gain_y",
    type="float",
    default=2500.0,
    min=0.0,
    max=1e8,
    ui_label="DPC phase-gradient gain (y)",
    group="Imaging",
    description="Scale factor for the y-gradient component in DPC.",
),
"dpc_phase_gradient_gain": ParamSpec(
    key="dpc_phase_gradient_gain",
    type="float",
    default=2500.0,
    min=0.0,
    max=1e8,
    ui_label="DPC phase-gradient gain",
    group="Imaging",
    description="Legacy fallback gain used when channel-specific gains are unset.",
),
"zernike_model": ParamSpec(
    key="zernike_model",
    type="enum",
    default="pupil_phase_ring",
    choices=["pupil_phase_ring", "fourier_phase_ring_proxy", "legacy_scalar_phase_proxy"],
    ui_label="Zernike phase model",
    group="Advanced modality",
    description=(
        "Zernike phase model for bright-field phase-contrast mode. The "
        "default applies the ring in objective-pupil coordinates."
    ),
),
"zernike_phase_ring_inner_fraction": ParamSpec(
    key="zernike_phase_ring_inner_fraction",
    type="float",
    default=0.0,
    min=0.0,
    max=1.0,
    ui_label="Zernike ring inner radius fraction",
    group="Advanced modality",
    description="Inner normalized radius of the Zernike phase ring; must stay below outer radius.",
),
"zernike_phase_ring_outer_fraction": ParamSpec(
    key="zernike_phase_ring_outer_fraction",
    type="float",
    default=0.15,
    min=0.0,
    max=1.0,
    ui_label="Zernike ring outer radius fraction",
    group="Advanced modality",
    description="Outer normalized radius of the Zernike phase ring.",
),
"zernike_phase_ring_shift_rad": ParamSpec(
    key="zernike_phase_ring_shift_rad",
    type="float",
    default=1.5707963267948966,
    min=-6.283185307179586,
    max=6.283185307179586,
    ui_label="Zernike ring phase shift (rad)",
    group="Advanced modality",
    description="Phase shift applied by the Zernike ring in radians.",
),
"zernike_phase_ring_amplitude": ParamSpec(
    key="zernike_phase_ring_amplitude",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Zernike ring amplitude",
    group="Advanced modality",
    description="Amplitude applied to Zernike phase contribution.",
),
"zernike_phase_ring_gain": ParamSpec(
    key="zernike_phase_ring_gain",
    type="float",
    default=0.35,
    min=0.0,
    max=1e6,
    ui_label="Zernike ring gain",
    group="Advanced modality",
    description="Gain factor for the Zernike ring pathway.",
),
"zernike_phase_bias": ParamSpec(
    key="zernike_phase_bias",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Zernike phase bias",
    group="Advanced modality",
    description="Bias offset on Zernike phase signal.",
),
"background_intensity": ParamSpec(
    key="background_intensity",
    type="float",
    default=100.0,
    min=0.0,
    max=500.0,
    ui_label="Background intensity",
    group="Imaging",
    description="Average background intensity level (camera counts).",
),
"kohler_coherence_factor": ParamSpec(
    key="kohler_coherence_factor",
    type="float",
    default=0.7,
    min=0.0,
    max=1.0,
    ui_label="Köhler coherence factor",
    group="Advanced modality",
    description="Coherence weighting for Köhler illumination models.",
),
"kohler_source_samples": ParamSpec(
    key="kohler_source_samples",
    type="int",
    default=19,
    min=1,
    max=4096,
    ui_label="Köhler source samples",
    group="Advanced modality",
    description="Number of samples used in Köhler source averaging.",
),
"annular_dark_field_inner_sigma": ParamSpec(
    key="annular_dark_field_inner_sigma",
    type="float",
    default=1.05,
    min=0.0,
    max=100.0,
    ui_label="Dark-field annulus inner sigma",
    group="Advanced modality",
    description="Inner annulus sigma for annular dark-field source model.",
),
"annular_dark_field_outer_sigma": ParamSpec(
    key="annular_dark_field_outer_sigma",
    type="float",
    default=1.30,
    min=0.0,
    max=100.0,
    ui_label="Dark-field annulus outer sigma",
    group="Advanced modality",
    description="Outer annulus sigma for annular dark-field source model.",
),
"annular_dark_field_source_samples": ParamSpec(
    key="annular_dark_field_source_samples",
    type="int",
    default=24,
    min=1,
    max=4096,
    ui_label="Dark-field source samples",
    group="Advanced modality",
    description="Sample count used for annular dark-field source-domain averaging.",
),
"dark_field_stop_radius_fraction": ParamSpec(
    key="dark_field_stop_radius_fraction",
    type="float",
    default=0.35,
    min=0.0,
    max=1.0,
    ui_label="Dark-field stop radius fraction",
    group="Advanced modality",
    description="Numerical aperture stop location as a fraction.",
),
"dark_field_field_gain": ParamSpec(
    key="dark_field_field_gain",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Dark-field field gain",
    group="Advanced modality",
    description="Amplitude gain applied to dark-field signal terms.",
),
"dark_field_sample_environment_edge_gain": ParamSpec(
    key="dark_field_sample_environment_edge_gain",
    type="float",
    default=0.02,
    min=0.0,
    max=1e6,
    ui_label="Dark-field substrate edge gain",
    group="Advanced modality",
    description="Gain for sample-environment edge-driven dark-field response.",
),
"dark_field_sample_environment_scatter_pedestal": ParamSpec(
    key="dark_field_sample_environment_scatter_pedestal",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="Dark-field scatter pedestal",
    group="Advanced modality",
    description="Additional uniform scatter pedestal in dark-field models.",
),
"dark_field_illumination_count": ParamSpec(
    key="dark_field_illumination_count",
    type="float",
    default=100.0,
    min=0.0,
    max=1e12,
    ui_label="Dark-field illumination count",
    group="Advanced modality",
    description="Scaling factor converting |E_sca|² to detector counts in dark-field.",
),
"dark_field_background_count": ParamSpec(
    key="dark_field_background_count",
    type="float",
    default=5.0,
    min=0.0,
    max=1e12,
    ui_label="Dark-field background count",
    group="Advanced modality",
    description="Baseline pedestal for dark-field modes.",
),
"bright_field_sample_environment_gain": ParamSpec(
    key="bright_field_sample_environment_gain",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Bright-field sample-environment gain",
    group="Advanced modality",
    description="Gain multiplier for sample-environment scattering in bright-field mode.",
),
"bright_field_sample_environment_phase_gain": ParamSpec(
    key="bright_field_sample_environment_phase_gain",
    type="float",
    default=0.05,
    min=0.0,
    max=1e6,
    ui_label="Bright-field sample-environment phase gain",
    group="Advanced modality",
    description="Phase-signal gain multiplier for sample-environment term in bright-field mode.",
),
"off_axis_fringe_period_px": ParamSpec(
    key="off_axis_fringe_period_px",
    type="float",
    default=10.0,
    min=0.1,
    max=1e6,
    ui_label="Off-axis fringe period (px)",
    group="Advanced modality",
    description="Fringe spatial period in pixels for off-axis holography.",
),
"off_axis_fringe_angle_rad": ParamSpec(
    key="off_axis_fringe_angle_rad",
    type="float",
    default=0.0,
    min=-6.283185307179586,
    max=6.283185307179586,
    ui_label="Off-axis fringe angle (rad)",
    group="Advanced modality",
    description="Fringe carrier angle in radians for off-axis holography.",
),
"ricm_interface_reflection_model": ParamSpec(
    key="ricm_interface_reflection_model",
    type="enum",
    default="fresnel",
    choices=["param", "fresnel", "thin_film_stack"],
    ui_label="RICM interface model",
    group="Advanced modality",
    description="Parametric, Fresnel, or thin-film-stack interface reflection model; Fresnel is the default physical interface path.",
),
"ricm_interface_reflection_coefficient": ParamSpec(
    key="ricm_interface_reflection_coefficient",
    type="float",
    default=0.2,
    min=-1e3,
    max=1e3,
    ui_label="RICM interface reflection coefficient",
    group="Advanced modality",
    description="Interface reflection coefficient used when model is 'param'.",
),
"ricm_interface_phase_shift_rad": ParamSpec(
    key="ricm_interface_phase_shift_rad",
    type="float",
    default=3.141592653589793,
    min=-6.283185307179586,
    max=6.283185307179586,
    ui_label="RICM interface phase shift (rad)",
    group="Advanced modality",
    description="Interface phase shift for the parametric interface reflection model.",
),
"ricm_interface_medium_material": ParamSpec(
    key="ricm_interface_medium_material",
    type="string",
    default="water",
    ui_label="RICM interface medium material",
    group="Advanced modality",
    description="Material on the medium side for interface reflection calculation.",
),
"ricm_interface_substrate_material": ParamSpec(
    key="ricm_interface_substrate_material",
    type="string",
    default="glass",
    ui_label="RICM interface substrate material",
    group="Advanced modality",
    description="Material on the substrate side for interface reflection calculation.",
),
"ricm_particle_medium_material": ParamSpec(
    key="ricm_particle_medium_material",
    type="string",
    default="water",
    ui_label="RICM particle medium material",
    group="Advanced modality",
    description="Medium material for particle-reflection calculations.",
),
"ricm_particle_reflection_coefficient": ParamSpec(
    key="ricm_particle_reflection_coefficient",
    type="float",
    default=0.04,
    min=-1e3,
    max=1e3,
    ui_label="RICM particle reflection coefficient",
    group="Advanced modality",
    description="Particle reflection coefficient used when model is 'param'.",
),
"ricm_particle_reflection_model": ParamSpec(
    key="ricm_particle_reflection_model",
    type="enum",
    default="fresnel",
    choices=["param", "fresnel"],
    ui_label="RICM particle reflection model",
    group="Advanced modality",
    description="Particle reflection model for RICM; Fresnel is the default material-aware path.",
),
"ricm_particle_material": ParamSpec(
    key="ricm_particle_material",
    type="string",
    default=None,
    ui_label="RICM particle material",
    group="Advanced modality",
    description="Optional explicit particle material for RICM calculations.",
),
"ricm_thinfilm_layers": ParamSpec(
    key="ricm_thinfilm_layers",
    type="json",
    default=[],
    ui_label="RICM thin-film layers",
    group="Advanced modality",
    description="Optional layered thin-film geometry specification for RICM interface calculations.",
),
"ricm_wavelength_nm": ParamSpec(
    key="ricm_wavelength_nm",
    type="float",
    default=532.0,
    min=1.0,
    max=1e6,
    ui_label="RICM wavelength (nm)",
    group="Advanced modality",
    description="Wavelength used by RICM optics.",
),
"fluorescence_collection_efficiency": ParamSpec(
    key="fluorescence_collection_efficiency",
    type="float",
    default=1.0,
    min=0.0,
    max=1.0,
    ui_label="Fluorescence collection efficiency",
    group="Advanced modality",
    description="Fraction of emitted photons collected by the optical train.",
),
"fluorescence_detector_qe": ParamSpec(
    key="fluorescence_detector_qe",
    type="float",
    default=1.0,
    min=0.0,
    max=1.0,
    ui_label="Fluorescence detector QE",
    group="Advanced modality",
    description=(
        "Fluorescence-path detector quantum efficiency. When set, this "
        "overrides PARAMS['detector_qe'] for fluorescence modalities only. "
        "If omitted, PARAMS['detector_qe'] is used as the fallback."
    ),
),
"fluorescence_backend": ParamSpec(
    key="fluorescence_backend",
    type="enum",
    default="vectorial_photophysics",
    choices=["parametric_psf", "vectorial_photophysics"],
    ui_label="Fluorescence backend",
    group="Advanced modality",
    description="Switch between parametric fluorescence and vectorial photophysics backends (vectorial default).",
),
"fluorescence_require_physical_photon_budget": ParamSpec(
    key="fluorescence_require_physical_photon_budget",
    type="bool",
    default=False,
    ui_label="Require physical fluorescence photon budget",
    group="Advanced modality",
    description=(
        "Require fluorescence_photons_per_fluorophore_per_frame for "
        "vectorial photophysics instead of accepting the legacy emitted "
        "photon scale."
    ),
),
"fluorescence_allow_psf_fallback": ParamSpec(
    key="fluorescence_allow_psf_fallback",
    type="bool",
    default=False,
    ui_label="Allow fluorescence PSF fallback",
    group="Advanced modality",
    description=(
        "Allow explicit Gaussian-proxy fallback if vectorial fluorescence "
        "PSF construction fails. Default false prevents silent fidelity "
        "downgrades."
    ),
),
"confocal_pinhole_sigma_nm": ParamSpec(
    key="confocal_pinhole_sigma_nm",
    type="float",
    default=350.0,
    min=1e-9,
    max=1e7,
    ui_label="Confocal axial sigma (nm)",
    group="Fluorescence",
    description="Gaussian axial detection weight used by optional confocal volumetric helper outputs.",
),
"light_sheet_center_z_nm": ParamSpec(
    key="light_sheet_center_z_nm",
    type="float",
    default=0.0,
    min=-1e7,
    max=1e7,
    ui_label="Light-sheet center z (nm)",
    group="Fluorescence",
    description="Axial center of the optional Gaussian light-sheet excitation helper.",
),
"light_sheet_sigma_nm": ParamSpec(
    key="light_sheet_sigma_nm",
    type="float",
    default=500.0,
    min=1e-9,
    max=1e7,
    ui_label="Light-sheet sigma (nm)",
    group="Fluorescence",
    description="Gaussian axial width of the optional light-sheet excitation helper.",
),
"fluorescence_reference_status": ParamSpec(
    key="fluorescence_reference_status",
    type="enum",
    default="physics_based_unvalidated",
    choices=["physics_based_unvalidated", "reference_validated"],
    ui_label="Fluorescence reference status",
    group="Advanced modality",
    description="Reference metadata state associated with fluorescence backend.",
),
"fluorescence_reference_validation_hash": ParamSpec(
    key="fluorescence_reference_validation_hash",
    type="string",
    default=None,
    ui_label="Fluorescence reference validation hash",
    group="Advanced modality",
    description="SHA-256 digest required when fluorescence_reference_status is reference_validated.",
),
"fluorescence_quantum_yield": ParamSpec(
    key="fluorescence_quantum_yield",
    type="float",
    default=0.5,
    min=0.0,
    max=1.0,
    ui_label="Fluorophore quantum yield",
    group="Advanced modality",
    description="Per-photon emission probability used by fluorescence generation.",
),
"fluorescence_excitation_scale": ParamSpec(
    key="fluorescence_excitation_scale",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Fluorescence excitation scale",
    group="Advanced modality",
    description="Multiplicative factor applied to fluorophore excitation map.",
),
"fluorescence_excitation_wavelength_nm": ParamSpec(
    key="fluorescence_excitation_wavelength_nm",
    type="float",
    default=488.0,
    min=1.0,
    max=10000.0,
    ui_label="Fluorescence excitation wavelength (nm)",
    group="Advanced modality",
    description="Excitation spectral line for fluorophore absorption weighting.",
),
"fluorescence_emission_wavelength_nm": ParamSpec(
    key="fluorescence_emission_wavelength_nm",
    type="float",
    default=520.0,
    min=1.0,
    max=10000.0,
    ui_label="Fluorescence emission wavelength (nm)",
    group="Advanced modality",
    description="Emission spectral line for fluorophore emission weighting.",
),
"fluorescence_spectral_bandwidth_nm": ParamSpec(
    key="fluorescence_spectral_bandwidth_nm",
    type="float",
    default=40.0,
    min=0.0,
    max=1000.0,
    ui_label="Fluorescence spectral bandwidth (nm)",
    group="Advanced modality",
    description="Gaussian bandwidth for spectral overlap weighting.",
),
"fluorescence_blinking_rate_per_frame": ParamSpec(
    key="fluorescence_blinking_rate_per_frame",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="Fluorescence blinking rate / frame",
    group="Advanced modality",
    description="Markov dark-to-bright transition rate for vectorial photophysics backend.",
),
"fluorescence_recovery_rate_per_frame": ParamSpec(
    key="fluorescence_recovery_rate_per_frame",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="Fluorescence recovery rate / frame",
    group="Advanced modality",
    description="Markov bright-to-dark recovery rate for vectorial photophysics backend.",
),
"fluorescence_bleaching_rate_per_frame": ParamSpec(
    key="fluorescence_bleaching_rate_per_frame",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="Fluorescence bleaching rate / frame",
    group="Advanced modality",
    description="Photobleaching rate for fluorophore occupancy decay.",
),
"fluorescence_background": ParamSpec(
    key="fluorescence_background",
    type="float",
    default=0.0,
    min=0.0,
    max=1e12,
    ui_label="Fluorescence uniform background",
    group="Advanced modality",
    description="Additive uniform fluorescence background in detected counts per pixel.",
),
"fluorescence_photobleach_tau_frames": ParamSpec(
    key="fluorescence_photobleach_tau_frames",
    type="float",
    default=None,
    min=0.0,
    max=1e12,
    ui_label="Fluorescence bleaching tau (frames)",
    group="Advanced modality",
    description="Alternative bleaching lifetime specification for compatibility.",
),
"fluorescence_photon_count_scale": ParamSpec(
    key="fluorescence_photon_count_scale",
    type="float",
    default=500.0,
    min=0.0,
    max=1e12,
    ui_label="Fluorescence photon count scale",
    group="Advanced modality",
    description=(
        "Legacy emitted-photon scale used when per-emitter photon counts "
        "are unset; collection efficiency and detector QE are applied "
        "after this scale."
    ),
),
"fluorescence_photons_per_fluorophore_per_frame": ParamSpec(
    key="fluorescence_photons_per_fluorophore_per_frame",
    type="float",
    default=None,
    min=0.0,
    max=1e12,
    ui_label="Fluorescence photons per fluorophore",
    group="Advanced modality",
    description="Per-emitter photon yield per frame.",
),
"fluorescence_emission_psf_sigma_nm": ParamSpec(
    key="fluorescence_emission_psf_sigma_nm",
    type="float",
    default=None,
    min=0.0,
    max=1000.0,
    ui_label="Fluorescence emission PSF sigma (nm)",
    group="Advanced modality",
    description="Emission PSF width in nanometers when provided.",
),
"fluorescence_emission_psf_sigma_px": ParamSpec(
    key="fluorescence_emission_psf_sigma_px",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Fluorescence emission PSF sigma (px)",
    group="Advanced modality",
    description="Emission PSF width in pixels when sigma-nm is unset.",
),
"fluorescence_sample_environment_excitation_modulation_gain": ParamSpec(
    key="fluorescence_sample_environment_excitation_modulation_gain",
    type="float",
    default=0.25,
    min=0.0,
    max=10.0,
    ui_label="Fluorescence sample-environment excitation modulation gain",
    group="Advanced modality",
    description="Multiplicative modulation applied to sample-environment excitation term.",
),
"fluorescence_sample_environment_autofluorescence_gain": ParamSpec(
    key="fluorescence_sample_environment_autofluorescence_gain",
    type="float",
    default=1.0,
    min=0.0,
    max=10.0,
    ui_label="Fluorescence sample-environment autofluorescence gain",
    group="Advanced modality",
    description="Gain applied to sample-environment autofluorescence term.",
),
"qpi_visibility": ParamSpec(
    key="qpi_visibility",
    type="float",
    default=1.0,
    min=0.001,
    max=1.0,
    ui_label="QPI visibility",
    group="Advanced modality",
    description="Interferometric visibility used for QPI phase-variance metadata.",
),
"qpi_detected_quanta_per_pixel": ParamSpec(
    key="qpi_detected_quanta_per_pixel",
    type="float",
    default=None,
    min=0.0,
    max=1e12,
    ui_label="QPI detected quanta / pixel",
    group="Advanced modality",
    description="Optional direct quanta-per-pixel calibration for QPI mode.",
),
"qpi_phase_to_count_scale": ParamSpec(
    key="qpi_phase_to_count_scale",
    type="float",
    default=100.0,
    min=1e-12,
    max=1e12,
    ui_label="QPI phase-to-count scale",
    group="Advanced modality",
    description="Scale factor converting phase to count-space contrast.",
),
"qpi_phase_noise_std_rad": ParamSpec(
    key="qpi_phase_noise_std_rad",
    type="float",
    default=None,
    min=0.0,
    max=3.141592653589793,
    ui_label="QPI phase noise sigma (rad)",
    group="Advanced modality",
    description="Optional phase-domain calibration noise floor in radians.",
),
"iscat_reference_model": ParamSpec(
    key="iscat_reference_model",
    type="enum",
    default="fresnel",
    choices=["renderer", "fresnel", "explicit"],
    ui_label="iSCAT reference model",
    group="Advanced modality",
    description="Reference field model for iSCAT contrast scaling; Fresnel is the default material-aware reference path.",
),
"iscat_reference_coefficient": ParamSpec(
    key="iscat_reference_coefficient",
    type="string",
    default="1.0",
    ui_label="iSCAT reference coefficient",
    group="Advanced modality",
    description=(
        "Explicit complex reference coefficient for iSCAT; accepts "
        "scalar, complex string, dict, or length-2 sequences."
    ),
),
"iscat_reference_medium_material": ParamSpec(
    key="iscat_reference_medium_material",
    type="string",
    default="water",
    ui_label="iSCAT reference medium",
    group="Advanced modality",
    description="Medium material for optional Fresnel reference calculation.",
),
"iscat_reference_substrate_material": ParamSpec(
    key="iscat_reference_substrate_material",
    type="string",
    default="glass",
    ui_label="iSCAT reference substrate",
    group="Advanced modality",
    description="Substrate material for optional Fresnel reference calculation.",
),
"iscat_reference_amplitude_scale": ParamSpec(
    key="iscat_reference_amplitude_scale",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="iSCAT reference amplitude scale",
    group="Advanced modality",
    description="Multiplicative scale on the optional iSCAT reference term.",
),
"iscat_reference_phase_rad": ParamSpec(
    key="iscat_reference_phase_rad",
    type="float",
    default=0.0,
    min=-6.283185307179586,
    max=6.283185307179586,
    ui_label="iSCAT reference phase (rad)",
    group="Advanced modality",
    description="Phase offset on the reference term used by iSCAT models.",
),
"iscat_reference_normalize_fresnel_phase_only": ParamSpec(
    key="iscat_reference_normalize_fresnel_phase_only",
    type="bool",
    default=False,
    ui_label="Normalize Fresnel phase only",
    group="Advanced modality",
    description="Normalize only Fresnel phase and keep amplitude unmodified.",
),
"iscat_collection_model": ParamSpec(
    key="iscat_collection_model",
    type="enum",
    default="dipole_high_na",
    choices=["scalar", "dipole", "dipole_high_na", "rayleigh_dipole"],
    ui_label="iSCAT collection model",
    group="Advanced modality",
    description="Collection response model for iSCAT dipole transport; high-NA dipole collection is the default material-aware path.",
),
"iscat_collection_reference_fraction": ParamSpec(
    key="iscat_collection_reference_fraction",
    type="float",
    default=1.0,
    min=1e-12,
    max=1e6,
    ui_label="iSCAT collection reference fraction",
    group="Advanced modality",
    description="Reference collection fraction used by dipole-based iSCAT models.",
),
"tirf_penetration_depth_nm": ParamSpec(
    key="tirf_penetration_depth_nm",
    type="float",
    default=120.0,
    min=0.0,
    max=1e6,
    ui_label="TIRF penetration depth (nm)",
    group="Advanced modality",
    description="Evanescent penetration depth used by TIRF fluorescence illumination.",
),
"tirf_prism_refractive_index": ParamSpec(
    key="tirf_prism_refractive_index",
    type="float",
    default=1.518,
    min=1.0,
    max=3.0,
    ui_label="TIRF prism refractive index",
    group="Advanced modality",
    description="Prism refractive index used in TIRF angle/depth calculations.",
),
"tirf_sample_refractive_index": ParamSpec(
    key="tirf_sample_refractive_index",
    type="float",
    default=1.333,
    min=1.0,
    max=3.0,
    ui_label="TIRF sample refractive index",
    group="Advanced modality",
    description="Sample refractive index used in TIRF geometry.",
),
"tirf_incident_angle_deg": ParamSpec(
    key="tirf_incident_angle_deg",
    type="float",
    default=66.0,
    min=0.0,
    max=180.0,
    ui_label="TIRF incident angle (deg)",
    group="Advanced modality",
    description="Incident angle used for TIRF fluorescence excitation.",
),
"tirf_particle_height_nm": ParamSpec(
    key="tirf_particle_height_nm",
    type="float",
    default=0.0,
    min=-1e9,
    max=1e9,
    ui_label="TIRF particle height (nm)",
    group="Advanced modality",
    description="Particle height above interface for TIRF excitation/extraction.",
),
"tirf_height_offset_nm": ParamSpec(
    key="tirf_height_offset_nm",
    type="float",
    default=0.0,
    min=-1e9,
    max=1e9,
    ui_label="TIRF height offset (nm)",
    group="Advanced modality",
    description="Static axial offset applied to TIRF particle height term.",
),
"tirf_effective_numerical_aperture": ParamSpec(
    key="tirf_effective_numerical_aperture",
    type="float",
    default=None,
    min=0.0,
    max=10.0,
    ui_label="TIRF effective NA",
    group="Advanced modality",
    description="Optional effective NA used by TIRF decay and excitation model.",
),
"tirf_use_angle_derived_penetration_depth": ParamSpec(
    key="tirf_use_angle_derived_penetration_depth",
    type="bool",
    default=False,
    ui_label="Derive penetration depth from angle",
    group="Advanced modality",
    description="Compute TIRF penetration depth from incident angle and refractive indices.",
),
}

__all__ = ["OPTICS_SCHEMA"]
