"""Particle parameter-schema fragment."""

from __future__ import annotations

from ._spec import ParamSpec


PARTICLE_SCHEMA: dict[str, ParamSpec] = {
"particle_diameter_nm": ParamSpec(
    key="particle_diameter_nm",
    container_key="particles",
    target_path="particles[0].components[0].diameter_nm",
    type="float",
    default=100.0,
    min=5.0,
    max=500.0,
    ui_label="Particle diameter (nm)",
    group="Particle",
    description="Optical diameter of the particle in nanometers.",
),
"particle_material": ParamSpec(
    key="particle_material",
    container_key="particles",
    target_path="particles[0].components[0].material",
    type="enum",
    default="Gold",
    choices=["Gold", "Silver", "Polystyrene"],
    ui_label="Particle material",
    group="Particle",
    description="Material label used for refractive index lookup.",
),
"z_motion_constraint_model": ParamSpec(
    key="z_motion_constraint_model",
    type="enum",
    default="unconstrained",
    choices=["unconstrained", "reflecting_floor_z0", "reflecting_ceiling_z0"],
    ui_label="Z-motion constraint model",
    group="Dynamics",
    description="Vertical motion model for particle trajectories.",
),
"vibration_jitter_std_nm": ParamSpec(
    key="vibration_jitter_std_nm",
    type="float",
    default=0.0,
    min=0.0,
    max=1e6,
    ui_label="Vibration jitter (nm)",
    group="Dynamics",
    description="Per-exposure Gaussian jitter applied as frame-wise position perturbation.",
),
"vibration_include_axial": ParamSpec(
    key="vibration_include_axial",
    type="bool",
    default=False,
    ui_label="Include axial vibration",
    group="Dynamics",
    description="Whether vibration perturbation includes the z-axis.",
),
"dynamic_bayesian_enabled": ParamSpec(
    key="dynamic_bayesian_enabled",
    type="bool",
    default=False,
    ui_label="Dynamic Bayesian CRLB",
    group="Dynamics",
    description="Enable dynamic CRLB estimation for frame sequences when num_frames>1.",
),
"sequence_fisher_enabled": ParamSpec(
    key="sequence_fisher_enabled",
    type="bool",
    default=False,
    ui_label="Sequence Fisher summary",
    group="Dynamics",
    description="Attach static cumulative sequence-Fisher summaries to matched modality packets when num_frames>1.",
),
"dynamic_process_noise_scale": ParamSpec(
    key="dynamic_process_noise_scale",
    type="float",
    default=1.0,
    min=0.0,
    max=1e6,
    ui_label="Dynamic prior scale",
    group="Dynamics",
    description="Non-negative scale factor applied to the Brownian process covariance used by the dynamic Bayesian CRLB.",
),
"dynamic_initial_variance_nm2": ParamSpec(
    key="dynamic_initial_variance_nm2",
    type="float",
    default=1.0e30,
    min=1e-12,
    max=1e90,
    ui_label="Dynamic initial variance",
    group="Dynamics",
    description="Initial state covariance variance (nm^2) before first frame when running sequence-wise Bayesian CRLB.",
),
"dynamic_include_smoothing": ParamSpec(
    key="dynamic_include_smoothing",
    type="bool",
    default=False,
    ui_label="Dynamic RTS smoothing",
    group="Dynamics",
    description="Enable RTS-style backward smoothing when computing dynamic Bayesian CRLB diagnostics.",
),
"initial_z_span_nm": ParamSpec(
    key="initial_z_span_nm",
    type="float",
    default=3000.0,
    min=0.0,
    max=1e9,
    ui_label="Initial z span (nm)",
    group="Dynamics",
    description="Initial Brownian z sampling span around the nominal axial position.",
),
"rotational_diffusion_enabled": ParamSpec(
    key="rotational_diffusion_enabled",
    type="bool",
    default=True,
    ui_label="Rotational diffusion enabled",
    group="Dynamics",
    description="Enable rotational diffusion in particle pose dynamics.",
),
"rotational_diffusion_mode": ParamSpec(
    key="rotational_diffusion_mode",
    type="enum",
    default="empirical",
    choices=["empirical", "stokes_einstein"],
    ui_label="Rotational diffusion mode",
    group="Dynamics",
    description="Choose empirical or Stokes-Einstein-based rotational diffusion.",
),
"rotational_step_std_deg": ParamSpec(
    key="rotational_step_std_deg",
    type="float",
    default=10.0,
    min=0.0,
    max=360.0,
    ui_label="Rotational step std (deg)",
    group="Dynamics",
    description="Per-frame angular standard deviation for empirical rotational updates.",
),
"temperature_K": ParamSpec(
    key="temperature_K",
    type="float",
    default=298.15,
    min=0.0,
    max=10000.0,
    ui_label="Temperature (K)",
    group="Dynamics",
    description="Physical temperature used by diffusion models.",
),
"viscosity_Pa_s": ParamSpec(
    key="viscosity_Pa_s",
    type="float",
    default=0.00089,
    min=1e-12,
    max=1e6,
    ui_label="Viscosity (Pa·s)",
    group="Dynamics",
    description="Medium dynamic viscosity for Brownian scaling.",
),
}

__all__ = ["PARTICLE_SCHEMA"]
