"""Substrate materials, environments, and patterned-surface utilities."""

from __future__ import annotations

from .environment import (
    Pattern,
    SampleEnvironment,
    Substrate,
    build_substrate_nuisance_basis,
    sample_environment_from_params,
)
from .materials import (
    AIR,
    CARBON,
    ComplexIndexModel,
    FLUORESCENT_POLYSTYRENE,
    GLASS,
    GOLD,
    LIPID,
    MaterialProperties,
    PET,
    POLYETHYLENE,
    POLYPROPYLENE,
    POLYSTYRENE,
    PROTEIN,
    SILVER,
    SI,
    SIO2,
    VACUUM,
    WATER,
    fresnel_reflection_amplitude,
    material_from_name,
)
from .patterns import (
    canonical_sample_environment_pattern_and_preset,
    clear_sample_environment_pattern_layout_cache,
    compute_contrast_scale_for_frame,
    generate_empirical_background_field,
    generate_reference_and_background_maps,
    generate_sample_environment_pattern_maps,
    generate_sample_environment_roughness_field,
    is_position_in_substrate_solid,
    project_position_to_fluid_region,
    reflect_position_across_substrate_boundary,
    resize_empirical_background_field,
)

__all__ = [
    "AIR",
    "CARBON",
    "ComplexIndexModel",
    "FLUORESCENT_POLYSTYRENE",
    "GLASS",
    "GOLD",
    "LIPID",
    "MaterialProperties",
    "PET",
    "POLYETHYLENE",
    "POLYPROPYLENE",
    "POLYSTYRENE",
    "PROTEIN",
    "Pattern",
    "SILVER",
    "SI",
    "SIO2",
    "SampleEnvironment",
    "Substrate",
    "VACUUM",
    "WATER",
    "build_substrate_nuisance_basis",
    "canonical_sample_environment_pattern_and_preset",
    "clear_sample_environment_pattern_layout_cache",
    "compute_contrast_scale_for_frame",
    "fresnel_reflection_amplitude",
    "generate_empirical_background_field",
    "generate_reference_and_background_maps",
    "generate_sample_environment_pattern_maps",
    "generate_sample_environment_roughness_field",
    "is_position_in_substrate_solid",
    "material_from_name",
    "project_position_to_fluid_region",
    "reflect_position_across_substrate_boundary",
    "resize_empirical_background_field",
    "sample_environment_from_params",
]
